#pragma once

// LogicCampaignData — typed facade over csv_logic/campaign.csv (class 21),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicCampaignData : public LogicData {
public:
    LogicCampaignData(const DataTables* tables, int row)
        : LogicData(tables, 21, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getLocation() const {
        return getString("Location");
    }
    [[nodiscard]] std::string getAllowedHeroes() const {
        return getString("AllowedHeroes");
    }
    [[nodiscard]] std::string getReward() const {
        return getString("Reward");
    }
    [[nodiscard]] int getLevelGenerationSeed() const {
        return getInt("LevelGenerationSeed");
    }
    [[nodiscard]] std::string getMap() const {
        return getString("Map");
    }
    [[nodiscard]] std::string getEnemies() const {
        return getString("Enemies");
    }
    [[nodiscard]] int getEnemyLevel() const {
        return getInt("EnemyLevel");
    }
    [[nodiscard]] std::string getBoss() const {
        return getString("Boss");
    }
    [[nodiscard]] int getBossLevel() const {
        return getInt("BossLevel");
    }
    [[nodiscard]] std::string getBase() const {
        return getString("Base");
    }
    [[nodiscard]] int getNumBases() const {
        return getInt("NumBases");
    }
    [[nodiscard]] int getBaseLevel() const {
        return getInt("BaseLevel");
    }
    [[nodiscard]] std::string getTower() const {
        return getString("Tower");
    }
    [[nodiscard]] int getNumTowers() const {
        return getInt("NumTowers");
    }
    [[nodiscard]] int getTowerLevel() const {
        return getInt("TowerLevel");
    }
    [[nodiscard]] int getRequiredStars() const {
        return getInt("RequiredStars");
    }
};

} // namespace titan
