#pragma once

// LogicGameModeVariationData — typed facade over csv_logic/game_mode_variations.csv (class 48),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicGameModeVariationData : public LogicData {
public:
    LogicGameModeVariationData(const DataTables* tables, int row)
        : LogicData(tables, 48, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getVariation() const {
        return getInt("Variation");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getShortName() const {
        return getString("ShortName");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getChatSuggestionItemName() const {
        return getString("ChatSuggestionItemName");
    }
    [[nodiscard]] std::string getGameModeRoomIconName() const {
        return getString("GameModeRoomIconName");
    }
    [[nodiscard]] std::string getGameModeIconName() const {
        return getString("GameModeIconName");
    }
    [[nodiscard]] std::string getBannerOverrideSWF() const {
        return getString("BannerOverrideSWF");
    }
    [[nodiscard]] std::string getBannerOverrideExportName() const {
        return getString("BannerOverrideExportName");
    }
    [[nodiscard]] std::string getSquareBannerOverrideSWF() const {
        return getString("SquareBannerOverrideSWF");
    }
    [[nodiscard]] std::string getSquareBannerOverrideExportName() const {
        return getString("SquareBannerOverrideExportName");
    }
    [[nodiscard]] std::string getScoreSfx() const {
        return getString("ScoreSfx");
    }
    [[nodiscard]] std::string getOpponentScoreSfx() const {
        return getString("OpponentScoreSfx");
    }
    [[nodiscard]] std::string getScoreText() const {
        return getString("ScoreText");
    }
    [[nodiscard]] std::string getScoreOpponentText() const {
        return getString("ScoreOpponentText");
    }
    [[nodiscard]] std::string getScoreTextEnd() const {
        return getString("ScoreTextEnd");
    }
    [[nodiscard]] std::string getScoreOpponentTextEnd() const {
        return getString("ScoreOpponentTextEnd");
    }
    [[nodiscard]] int getFriendlyMenuOrder() const {
        return getInt("FriendlyMenuOrder");
    }
    [[nodiscard]] std::string getIntroText() const {
        return getString("IntroText");
    }
    [[nodiscard]] std::string getIntroDescText() const {
        return getString("IntroDescText");
    }
    [[nodiscard]] std::string getIntroDescText2() const {
        return getString("IntroDescText2");
    }
    [[nodiscard]] std::string getStartNotification() const {
        return getString("StartNotification");
    }
    [[nodiscard]] std::string getEndNotification() const {
        return getString("EndNotification");
    }
    [[nodiscard]] std::string getColor() const {
        return getString("Color");
    }
    [[nodiscard]] std::string getFallbackPlayerMapEnvironment() const {
        return getString("FallbackPlayerMapEnvironment");
    }
};

} // namespace titan
