#pragma once

// LogicSkinData — typed facade over csv_logic/skins.csv (class 29),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicSkinData : public LogicData {
public:
    LogicSkinData(const DataTables* tables, int row)
        : LogicData(tables, 29, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getConf() const {
        return getString("Conf");
    }
    [[nodiscard]] std::string getCampaign() const {
        return getString("Campaign");
    }
    [[nodiscard]] std::string getIconOverride() const {
        return getString("IconOverride");
    }
    [[nodiscard]] int getSkinGroupId() const {
        return getInt("SkinGroupId");
    }
    [[nodiscard]] int getObtainType() const {
        return getInt("ObtainType");
    }
    [[nodiscard]] int getObtainTypeCN() const {
        return getInt("ObtainTypeCN");
    }
    [[nodiscard]] bool getLastChance() const {
        return getBool("LastChance");
    }
    [[nodiscard]] std::string getMasterSkin() const {
        return getString("MasterSkin");
    }
    [[nodiscard]] std::string getPetSkin() const {
        return getString("PetSkin");
    }
    [[nodiscard]] std::string getPetSkin2() const {
        return getString("PetSkin2");
    }
    [[nodiscard]] int getCostStarPoints() const {
        return getInt("CostStarPoints");
    }
    [[nodiscard]] int getCostGems() const {
        return getInt("CostGems");
    }
    [[nodiscard]] int getCostCoins() const {
        return getInt("CostCoins");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getShopTID() const {
        return getString("ShopTID");
    }
    [[nodiscard]] std::string getFeatures() const {
        return getString("Features");
    }
    [[nodiscard]] std::string getCommunityCredit() const {
        return getString("CommunityCredit");
    }
    [[nodiscard]] std::string getMaterialsFile() const {
        return getString("MaterialsFile");
    }
    [[nodiscard]] std::string getBlueTexture() const {
        return getString("BlueTexture");
    }
    [[nodiscard]] std::string getRedTexture() const {
        return getString("RedTexture");
    }
    [[nodiscard]] std::string getBlueSpecular() const {
        return getString("BlueSpecular");
    }
    [[nodiscard]] std::string getRedSpecular() const {
        return getString("RedSpecular");
    }
    [[nodiscard]] std::string getOutlineShader() const {
        return getString("OutlineShader");
    }
};

} // namespace titan
