#pragma once

// LogicEffectData — typed facade over csv_client/effects.csv (class 7),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicEffectData : public LogicData {
public:
    LogicEffectData(const DataTables* tables, int row)
        : LogicData(tables, 7, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getLoop() const {
        return getBool("Loop");
    }
    [[nodiscard]] bool getFollowParent() const {
        return getBool("FollowParent");
    }
    [[nodiscard]] bool getFollowParentAngle() const {
        return getBool("FollowParentAngle");
    }
    [[nodiscard]] std::string getFollowBone() const {
        return getString("FollowBone");
    }
    [[nodiscard]] int getOwnScreenShake() const {
        return getInt("OwnScreenShake");
    }
    [[nodiscard]] int getOthersScreenShake() const {
        return getInt("OthersScreenShake");
    }
    [[nodiscard]] int getTime() const {
        return getInt("Time");
    }
    [[nodiscard]] std::string getSound() const {
        return getString("Sound");
    }
    [[nodiscard]] std::string getType() const {
        return getString("Type");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
    [[nodiscard]] std::string getParticleEmitterName() const {
        return getString("ParticleEmitterName");
    }
    [[nodiscard]] std::string getEffect() const {
        return getString("Effect");
    }
    [[nodiscard]] std::string getLayer() const {
        return getString("Layer");
    }
    [[nodiscard]] bool getGroundBasis() const {
        return getBool("GroundBasis");
    }
    [[nodiscard]] int getFlashColor() const {
        return getInt("FlashColor");
    }
    [[nodiscard]] int getScale() const {
        return getInt("Scale");
    }
    [[nodiscard]] int getFlashDuration() const {
        return getInt("FlashDuration");
    }
    [[nodiscard]] std::string getTextInstanceName() const {
        return getString("TextInstanceName");
    }
    [[nodiscard]] std::string getTextParentInstanceName() const {
        return getString("TextParentInstanceName");
    }
    [[nodiscard]] std::string getEnemyVersion() const {
        return getString("EnemyVersion");
    }
    [[nodiscard]] std::string getChinaReplacement() const {
        return getString("ChinaReplacement");
    }
    [[nodiscard]] int getFlashWidth() const {
        return getInt("FlashWidth");
    }
    [[nodiscard]] int getEffectZ() const {
        return getInt("EffectZ");
    }
};

} // namespace titan
