#pragma once

// LogicSkinRarityData — typed facade over csv_logic/skinsrarity.csv (class 38),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicSkinRarityData : public LogicData {
public:
    LogicSkinRarityData(const DataTables* tables, int row)
        : LogicData(tables, 38, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getPrice() const {
        return getInt("Price");
    }
    [[nodiscard]] int getRarity() const {
        return getInt("Rarity");
    }
};

} // namespace titan
