#pragma once

// LogicMusicData — typed facade over csv_client/music.csv (class 12),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicMusicData : public LogicData {
public:
    LogicMusicData(const DataTables* tables, int row)
        : LogicData(tables, 12, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] bool getBackgroundFile() const {
        return getBool("BackgroundFile");
    }
    [[nodiscard]] std::string getFallBackMusic() const {
        return getString("FallBackMusic");
    }
    [[nodiscard]] int getVolume() const {
        return getInt("Volume");
    }
    [[nodiscard]] bool getLoop() const {
        return getBool("Loop");
    }
    [[nodiscard]] int getPlayCount() const {
        return getInt("PlayCount");
    }
    [[nodiscard]] int getFadeOutTimeSec() const {
        return getInt("FadeOutTimeSec");
    }
    [[nodiscard]] int getDurationSec() const {
        return getInt("DurationSec");
    }
    [[nodiscard]] std::string getMovieClipFrameLabel() const {
        return getString("MovieClipFrameLabel");
    }
};

} // namespace titan
