#pragma once

// LogicProjectileData — typed facade over csv_logic/projectiles.csv (class 6),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicProjectileData : public LogicData {
public:
    LogicProjectileData(const DataTables* tables, int row)
        : LogicData(tables, 6, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getParentProjectileForSkin() const {
        return getString("ParentProjectileForSkin");
    }
    [[nodiscard]] int getSpeed() const {
        return getInt("Speed");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getBlueSCW() const {
        return getString("BlueSCW");
    }
    [[nodiscard]] std::string getRedSCW() const {
        return getString("RedSCW");
    }
    [[nodiscard]] std::string getBlueExportName() const {
        return getString("BlueExportName");
    }
    [[nodiscard]] std::string getRedExportName() const {
        return getString("RedExportName");
    }
    [[nodiscard]] std::string getShadowExportName() const {
        return getString("ShadowExportName");
    }
    [[nodiscard]] std::string getBlueGroundGlowExportName() const {
        return getString("BlueGroundGlowExportName");
    }
    [[nodiscard]] std::string getRedGroundGlowExportName() const {
        return getString("RedGroundGlowExportName");
    }
    [[nodiscard]] std::string getPreExplosionBlueExportName() const {
        return getString("PreExplosionBlueExportName");
    }
    [[nodiscard]] std::string getPreExplosionRedExportName() const {
        return getString("PreExplosionRedExportName");
    }
    [[nodiscard]] int getPreExplosionTimeMs() const {
        return getInt("PreExplosionTimeMs");
    }
    [[nodiscard]] std::string getHitEffectEnv() const {
        return getString("HitEffectEnv");
    }
    [[nodiscard]] std::string getHitEffectChar() const {
        return getString("HitEffectChar");
    }
    [[nodiscard]] std::string getMaxRangeReachedEffect() const {
        return getString("MaxRangeReachedEffect");
    }
    [[nodiscard]] std::string getCancelEffect() const {
        return getString("CancelEffect");
    }
    [[nodiscard]] int getRadius() const {
        return getInt("Radius");
    }
    [[nodiscard]] bool getIndirect() const {
        return getBool("Indirect");
    }
    [[nodiscard]] bool getConstantFlyTime() const {
        return getBool("ConstantFlyTime");
    }
    [[nodiscard]] int getTriggerWithDelayMs() const {
        return getInt("TriggerWithDelayMs");
    }
    [[nodiscard]] int getBouncePercent() const {
        return getInt("BouncePercent");
    }
    [[nodiscard]] int getGravity() const {
        return getInt("Gravity");
    }
    [[nodiscard]] int getEarlyTicks() const {
        return getInt("EarlyTicks");
    }
    [[nodiscard]] int getHideTime() const {
        return getInt("HideTime");
    }
    [[nodiscard]] int getScale() const {
        return getInt("Scale");
    }
    [[nodiscard]] int getRandomStartFrame() const {
        return getInt("RandomStartFrame");
    }
    [[nodiscard]] std::string getSpawnAreaEffectObject() const {
        return getString("SpawnAreaEffectObject");
    }
    [[nodiscard]] std::string getSpawnAreaEffectObject2() const {
        return getString("SpawnAreaEffectObject2");
    }
    [[nodiscard]] std::string getSpawnCharacter() const {
        return getString("SpawnCharacter");
    }
    [[nodiscard]] std::string getSpawnItem() const {
        return getString("SpawnItem");
    }
    [[nodiscard]] std::string getSpawnAreaEffectTrail() const {
        return getString("SpawnAreaEffectTrail");
    }
    [[nodiscard]] std::string getTrailEffect() const {
        return getString("TrailEffect");
    }
    [[nodiscard]] bool getShotByHero() const {
        return getBool("ShotByHero");
    }
    [[nodiscard]] bool getIsBeam() const {
        return getBool("IsBeam");
    }
    [[nodiscard]] bool getIsBouncing() const {
        return getBool("IsBouncing");
    }
    [[nodiscard]] int getDistanceAddFromBounce() const {
        return getInt("DistanceAddFromBounce");
    }
    [[nodiscard]] int getMaxDistanceBounces() const {
        return getInt("MaxDistanceBounces");
    }
    [[nodiscard]] std::string getRendering() const {
        return getString("Rendering");
    }
    [[nodiscard]] bool getPiercesCharacters() const {
        return getBool("PiercesCharacters");
    }
    [[nodiscard]] bool getPiercesEnvironment() const {
        return getBool("PiercesEnvironment");
    }
    [[nodiscard]] bool getPiercesEnvironmentLikeButter() const {
        return getBool("PiercesEnvironmentLikeButter");
    }
    [[nodiscard]] int getPushbackStrength() const {
        return getInt("PushbackStrength");
    }
    [[nodiscard]] int getPushbackType() const {
        return getInt("PushbackType");
    }
    [[nodiscard]] int getChainsToEnemies() const {
        return getInt("ChainsToEnemies");
    }
    [[nodiscard]] int getChainBullets() const {
        return getInt("ChainBullets");
    }
    [[nodiscard]] int getChainSpread() const {
        return getInt("ChainSpread");
    }
    [[nodiscard]] int getChainTravelDistance() const {
        return getInt("ChainTravelDistance");
    }
    [[nodiscard]] std::string getChainBullet() const {
        return getString("ChainBullet");
    }
    [[nodiscard]] int getExecuteChainSpecialCase() const {
        return getInt("ExecuteChainSpecialCase");
    }
    [[nodiscard]] int getDamagePercentStart() const {
        return getInt("DamagePercentStart");
    }
    [[nodiscard]] int getDamagePercentEnd() const {
        return getInt("DamagePercentEnd");
    }
    [[nodiscard]] int getDamageChangeStartPromille() const {
        return getInt("DamageChangeStartPromille");
    }
    [[nodiscard]] int getDamageChangeEndPromille() const {
        return getInt("DamageChangeEndPromille");
    }
    [[nodiscard]] bool getIgnoreDamageChangeForUltiCharge() const {
        return getBool("IgnoreDamageChangeForUltiCharge");
    }
    [[nodiscard]] int getDamagesConstantlyTickDelay() const {
        return getInt("DamagesConstantlyTickDelay");
    }
    [[nodiscard]] int getFreezeStrength() const {
        return getInt("FreezeStrength");
    }
    [[nodiscard]] int getFreezeDurationMS() const {
        return getInt("FreezeDurationMS");
    }
    [[nodiscard]] int getStunLengthMS() const {
        return getInt("StunLengthMS");
    }
    [[nodiscard]] int getPartialStunPromille() const {
        return getInt("PartialStunPromille");
    }
    [[nodiscard]] int getScaleStart() const {
        return getInt("ScaleStart");
    }
    [[nodiscard]] int getScaleEnd() const {
        return getInt("ScaleEnd");
    }
    [[nodiscard]] bool getAttractsPet() const {
        return getBool("AttractsPet");
    }
    [[nodiscard]] int getLifeStealPercent() const {
        return getInt("LifeStealPercent");
    }
    [[nodiscard]] bool getPassesEnvironment() const {
        return getBool("PassesEnvironment");
    }
    [[nodiscard]] int getPoisonDamagePercent() const {
        return getInt("PoisonDamagePercent");
    }
    [[nodiscard]] int getSuppressHealing() const {
        return getInt("SuppressHealing");
    }
    [[nodiscard]] int getSuppressHealingTicks() const {
        return getInt("SuppressHealingTicks");
    }
    [[nodiscard]] bool getDamageOnlyWithOneProj() const {
        return getBool("DamageOnlyWithOneProj");
    }
    [[nodiscard]] int getHealOwnPercent() const {
        return getInt("HealOwnPercent");
    }
    [[nodiscard]] bool getCanGrowStronger() const {
        return getBool("CanGrowStronger");
    }
    [[nodiscard]] bool getHideFaster() const {
        return getBool("HideFaster");
    }
    [[nodiscard]] bool getGrapplesEnemy() const {
        return getBool("GrapplesEnemy");
    }
    [[nodiscard]] int getKickBack() const {
        return getInt("KickBack");
    }
    [[nodiscard]] bool getUseColorMod() const {
        return getBool("UseColorMod");
    }
    [[nodiscard]] int getRedAdd() const {
        return getInt("RedAdd");
    }
    [[nodiscard]] int getGreenAdd() const {
        return getInt("GreenAdd");
    }
    [[nodiscard]] int getBlueAdd() const {
        return getInt("BlueAdd");
    }
    [[nodiscard]] int getRedMul() const {
        return getInt("RedMul");
    }
    [[nodiscard]] int getGreenMul() const {
        return getInt("GreenMul");
    }
    [[nodiscard]] int getBlueMul() const {
        return getInt("BlueMul");
    }
    [[nodiscard]] bool getGroundBasis() const {
        return getBool("GroundBasis");
    }
    [[nodiscard]] int getMinDistanceForSpread() const {
        return getInt("MinDistanceForSpread");
    }
    [[nodiscard]] bool getIsFriendlyHomingMissile() const {
        return getBool("IsFriendlyHomingMissile");
    }
    [[nodiscard]] bool getIsBoomerang() const {
        return getBool("IsBoomerang");
    }
    [[nodiscard]] bool getCanHitAgainAfterBounce() const {
        return getBool("CanHitAgainAfterBounce");
    }
    [[nodiscard]] bool getIsHomingMissile() const {
        return getBool("IsHomingMissile");
    }
    [[nodiscard]] bool getBlockUltiCharge() const {
        return getBool("BlockUltiCharge");
    }
    [[nodiscard]] int getPoisonType() const {
        return getInt("PoisonType");
    }
    [[nodiscard]] int getAppliedEffectVisualType() const {
        return getInt("AppliedEffectVisualType");
    }
    [[nodiscard]] int getTravelType() const {
        return getInt("TravelType");
    }
    [[nodiscard]] int getTravelTypeVariable() const {
        return getInt("TravelTypeVariable");
    }
    [[nodiscard]] int getSteerStrength() const {
        return getInt("SteerStrength");
    }
    [[nodiscard]] int getSteerIgnoreTicks() const {
        return getInt("SteerIgnoreTicks");
    }
    [[nodiscard]] int getHomeDistance() const {
        return getInt("HomeDistance");
    }
    [[nodiscard]] int getSteerLifeTime() const {
        return getInt("SteerLifeTime");
    }
    [[nodiscard]] bool getVisualizeEndPoint() const {
        return getBool("VisualizeEndPoint");
    }
    [[nodiscard]] int getUniqueProperty() const {
        return getInt("UniqueProperty");
    }
    [[nodiscard]] int getCustomUniquePropertyValue() const {
        return getInt("CustomUniquePropertyValue");
    }
    [[nodiscard]] std::string getCustomObject() const {
        return getString("CustomObject");
    }
};

} // namespace titan
