#pragma once

// LogicChallengeData — typed facade over csv_logic/challenges.csv (class 49),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicChallengeData : public LogicData {
public:
    LogicChallengeData(const DataTables* tables, int row)
        : LogicData(tables, 49, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] int getChallengeId() const {
        return getInt("ChallengeId");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getLocale() const {
        return getString("Locale");
    }
    [[nodiscard]] std::string getLogoAsset() const {
        return getString("LogoAsset");
    }
    [[nodiscard]] std::string getHomeScreenLogo() const {
        return getString("HomeScreenLogo");
    }
    [[nodiscard]] std::string getEventAsset() const {
        return getString("EventAsset");
    }
    [[nodiscard]] std::string getChatItem() const {
        return getString("ChatItem");
    }
    [[nodiscard]] std::string getRewardItem() const {
        return getString("RewardItem");
    }
    [[nodiscard]] std::string getRewardUnlockedItem() const {
        return getString("RewardUnlockedItem");
    }
    [[nodiscard]] std::string getHeaderFrame() const {
        return getString("HeaderFrame");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getStageTID() const {
        return getString("StageTID");
    }
    [[nodiscard]] std::string getRewardTID() const {
        return getString("RewardTID");
    }
    [[nodiscard]] std::string getCompletedTID() const {
        return getString("CompletedTID");
    }
    [[nodiscard]] std::string getMilestoneRewardPopupTID() const {
        return getString("MilestoneRewardPopupTID");
    }
    [[nodiscard]] std::string getCompletionRewardPopupTID() const {
        return getString("CompletionRewardPopupTID");
    }
    [[nodiscard]] std::string getBattleEndHeaderTID() const {
        return getString("BattleEndHeaderTID");
    }
    [[nodiscard]] std::string getBattleEndWinLabelTID() const {
        return getString("BattleEndWinLabelTID");
    }
    [[nodiscard]] std::string getBattleEndWinTID() const {
        return getString("BattleEndWinTID");
    }
    [[nodiscard]] std::string getStartNotification() const {
        return getString("StartNotification");
    }
    [[nodiscard]] std::string getReminderNotification() const {
        return getString("ReminderNotification");
    }
    [[nodiscard]] std::string getTeaserTitleTID() const {
        return getString("TeaserTitleTID");
    }
    [[nodiscard]] std::string getTeaserInfoTID() const {
        return getString("TeaserInfoTID");
    }
    [[nodiscard]] std::string getRewardSkin() const {
        return getString("RewardSkin");
    }
    [[nodiscard]] std::string getRewardPopupTID() const {
        return getString("RewardPopupTID");
    }
};

} // namespace titan
