#pragma once

// LogicFaceData — typed facade over csv_client/faces.csv (class 30),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicFaceData : public LogicData {
public:
    LogicFaceData(const DataTables* tables, int row)
        : LogicData(tables, 30, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
};

} // namespace titan
