#pragma once

// LogicLocationData — typed facade over csv_logic/locations.csv (class 15),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicLocationData : public LogicData {
public:
    LogicLocationData(const DataTables* tables, int row)
        : LogicData(tables, 15, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getLocationTheme() const {
        return getString("LocationTheme");
    }
    [[nodiscard]] bool getSupportingCampaignGround() const {
        return getBool("SupportingCampaignGround");
    }
    [[nodiscard]] std::string getBannerOverrideSWF() const {
        return getString("BannerOverrideSWF");
    }
    [[nodiscard]] std::string getBannerOverrideExportName() const {
        return getString("BannerOverrideExportName");
    }
    [[nodiscard]] std::string getGameModeVariation() const {
        return getString("GameModeVariation");
    }
    [[nodiscard]] std::string getMap() const {
        return getString("Map");
    }
    [[nodiscard]] std::string getCommunityCredit() const {
        return getString("CommunityCredit");
    }
};

} // namespace titan
