#pragma once

// LogicMessageData — typed facade over csv_logic/messages.csv (class 40),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicMessageData : public LogicData {
public:
    LogicMessageData(const DataTables* tables, int row)
        : LogicData(tables, 40, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getBubbleOverrideTID() const {
        return getString("BubbleOverrideTID");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] int getMessageType() const {
        return getInt("MessageType");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
    [[nodiscard]] int getQuickEmojiType() const {
        return getInt("QuickEmojiType");
    }
    [[nodiscard]] int getSortPriority() const {
        return getInt("SortPriority");
    }
    [[nodiscard]] bool getAgeGated() const {
        return getBool("AgeGated");
    }
};

} // namespace titan
