#pragma once

// LogicEmoteData — typed facade over csv_logic/emotes.csv (class 52),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicEmoteData : public LogicData {
public:
    LogicEmoteData(const DataTables* tables, int row)
        : LogicData(tables, 52, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
    [[nodiscard]] std::string getCharacter() const {
        return getString("Character");
    }
    [[nodiscard]] std::string getSkin() const {
        return getString("Skin");
    }
    [[nodiscard]] bool getIsPicto() const {
        return getBool("IsPicto");
    }
    [[nodiscard]] int getBattleCategory() const {
        return getInt("BattleCategory");
    }
    [[nodiscard]] int getRarity() const {
        return getInt("Rarity");
    }
    [[nodiscard]] int getEmoteType() const {
        return getInt("EmoteType");
    }
    [[nodiscard]] std::string getSoundEffect() const {
        return getString("SoundEffect");
    }
    [[nodiscard]] int getSfxIndex() const {
        return getInt("SfxIndex");
    }
    [[nodiscard]] bool getLockedForChronos() const {
        return getBool("LockedForChronos");
    }
    [[nodiscard]] std::string getEmoteBundle() const {
        return getString("EmoteBundle");
    }
    [[nodiscard]] bool getIsDefaultBattleEmote() const {
        return getBool("IsDefaultBattleEmote");
    }
};

} // namespace titan
