#pragma once

// LogicParticleEmitterData — typed facade over csv_client/particle_emitters.csv (class 10),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicParticleEmitterData : public LogicData {
public:
    LogicParticleEmitterData(const DataTables* tables, int row)
        : LogicData(tables, 10, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getMaxParticleCount() const {
        return getInt("MaxParticleCount");
    }
    [[nodiscard]] int getMinLife() const {
        return getInt("MinLife");
    }
    [[nodiscard]] int getMaxLife() const {
        return getInt("MaxLife");
    }
    [[nodiscard]] int getParticleMinInterval() const {
        return getInt("ParticleMinInterval");
    }
    [[nodiscard]] int getParticleMaxInterval() const {
        return getInt("ParticleMaxInterval");
    }
    [[nodiscard]] int getParticleMinLife() const {
        return getInt("ParticleMinLife");
    }
    [[nodiscard]] int getParticleMaxLife() const {
        return getInt("ParticleMaxLife");
    }
    [[nodiscard]] int getParticleMinAngle() const {
        return getInt("ParticleMinAngle");
    }
    [[nodiscard]] int getParticleMaxAngle() const {
        return getInt("ParticleMaxAngle");
    }
    [[nodiscard]] bool getParticleAngleRelativeToParent() const {
        return getBool("ParticleAngleRelativeToParent");
    }
    [[nodiscard]] bool getParticleRandomAngle() const {
        return getBool("ParticleRandomAngle");
    }
    [[nodiscard]] int getParticleMinRadius() const {
        return getInt("ParticleMinRadius");
    }
    [[nodiscard]] int getParticleMaxRadius() const {
        return getInt("ParticleMaxRadius");
    }
    [[nodiscard]] int getParticleMinSpeed() const {
        return getInt("ParticleMinSpeed");
    }
    [[nodiscard]] int getParticleMaxSpeed() const {
        return getInt("ParticleMaxSpeed");
    }
    [[nodiscard]] int getParticleStartZ() const {
        return getInt("ParticleStartZ");
    }
    [[nodiscard]] int getParticleMinVelocityZ() const {
        return getInt("ParticleMinVelocityZ");
    }
    [[nodiscard]] int getParticleMaxVelocityZ() const {
        return getInt("ParticleMaxVelocityZ");
    }
    [[nodiscard]] int getParticleGravity() const {
        return getInt("ParticleGravity");
    }
    [[nodiscard]] int getParticleMinTailLength() const {
        return getInt("ParticleMinTailLength");
    }
    [[nodiscard]] int getParticleMaxTailLength() const {
        return getInt("ParticleMaxTailLength");
    }
    [[nodiscard]] std::string getParticleResource() const {
        return getString("ParticleResource");
    }
    [[nodiscard]] std::string getParticleExportName() const {
        return getString("ParticleExportName");
    }
    [[nodiscard]] bool getRotateToDirection() const {
        return getBool("RotateToDirection");
    }
    [[nodiscard]] bool getLoopParticleClip() const {
        return getBool("LoopParticleClip");
    }
    [[nodiscard]] int getStartScale() const {
        return getInt("StartScale");
    }
    [[nodiscard]] int getEndScale() const {
        return getInt("EndScale");
    }
    [[nodiscard]] int getFadeOutDuration() const {
        return getInt("FadeOutDuration");
    }
    [[nodiscard]] int getInertia() const {
        return getInt("Inertia");
    }
    [[nodiscard]] std::string getEnemyVersion() const {
        return getString("EnemyVersion");
    }
};

} // namespace titan
