#pragma once

// LogicResourceData — typed facade over csv_logic/resources.csv (class 5),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicResourceData : public LogicData {
public:
    LogicResourceData(const DataTables* tables, int row)
        : LogicData(tables, 5, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getCollectEffect() const {
        return getString("CollectEffect");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] std::string getType() const {
        return getString("Type");
    }
    [[nodiscard]] std::string getRarity() const {
        return getString("Rarity");
    }
    [[nodiscard]] bool getPremiumCurrency() const {
        return getBool("PremiumCurrency");
    }
    [[nodiscard]] int getTextRed() const {
        return getInt("TextRed");
    }
    [[nodiscard]] int getTextGreen() const {
        return getInt("TextGreen");
    }
    [[nodiscard]] int getTextBlue() const {
        return getInt("TextBlue");
    }
    [[nodiscard]] int getCap() const {
        return getInt("Cap");
    }
};

} // namespace titan
