#pragma once

// LogicItemData — typed facade over csv_logic/items.csv (class 18),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicItemData : public LogicData {
public:
    LogicItemData(const DataTables* tables, int row)
        : LogicData(tables, 18, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getParentItemForSkin() const {
        return getString("ParentItemForSkin");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
    [[nodiscard]] std::string getExportNameEnemy() const {
        return getString("ExportNameEnemy");
    }
    [[nodiscard]] std::string getShadowExportName() const {
        return getString("ShadowExportName");
    }
    [[nodiscard]] std::string getGroundGlowExportName() const {
        return getString("GroundGlowExportName");
    }
    [[nodiscard]] std::string getLoopingEffect() const {
        return getString("LoopingEffect");
    }
    [[nodiscard]] bool getAlignToTiles() const {
        return getBool("AlignToTiles");
    }
    [[nodiscard]] int getValue() const {
        return getInt("Value");
    }
    [[nodiscard]] int getValue2() const {
        return getInt("Value2");
    }
    [[nodiscard]] int getLifetime() const {
        return getInt("Lifetime");
    }
    [[nodiscard]] int getTriggerRangeSubTiles() const {
        return getInt("TriggerRangeSubTiles");
    }
    [[nodiscard]] std::string getTriggerAreaEffect() const {
        return getString("TriggerAreaEffect");
    }
    [[nodiscard]] bool getCanBePickedUp() const {
        return getBool("CanBePickedUp");
    }
    [[nodiscard]] std::string getSpawnEffect() const {
        return getString("SpawnEffect");
    }
    [[nodiscard]] std::string getActivateEffect() const {
        return getString("ActivateEffect");
    }
    [[nodiscard]] std::string getSCW() const {
        return getString("SCW");
    }
    [[nodiscard]] std::string getSCWEnemy() const {
        return getString("SCWEnemy");
    }
    [[nodiscard]] std::string getSCWTopLayer() const {
        return getString("SCWTopLayer");
    }
    [[nodiscard]] bool getUseGeneratedShadow() const {
        return getBool("UseGeneratedShadow");
    }
    [[nodiscard]] bool getShowAlways() const {
        return getBool("ShowAlways");
    }
    [[nodiscard]] int getRandomStartFrame() const {
        return getInt("RandomStartFrame");
    }
    [[nodiscard]] std::string getLayer() const {
        return getString("Layer");
    }
};

} // namespace titan
