#pragma once

// LogicTileData — typed facade over csv_logic/tiles.csv (class 27),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicTileData : public LogicData {
public:
    LogicTileData(const DataTables* tables, int row)
        : LogicData(tables, 27, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTileCode() const {
        return getString("TileCode");
    }
    [[nodiscard]] int getDynamicCode() const {
        return getInt("DynamicCode");
    }
    [[nodiscard]] bool getBlocksMovement() const {
        return getBool("BlocksMovement");
    }
    [[nodiscard]] bool getBlocksProjectiles() const {
        return getBool("BlocksProjectiles");
    }
    [[nodiscard]] bool getIsDestructible() const {
        return getBool("IsDestructible");
    }
    [[nodiscard]] bool getIsDestructibleNormalWeapon() const {
        return getBool("IsDestructibleNormalWeapon");
    }
    [[nodiscard]] bool getHidesHero() const {
        return getBool("HidesHero");
    }
    [[nodiscard]] int getDamage() const {
        return getInt("Damage");
    }
    [[nodiscard]] int getSpeedChange() const {
        return getInt("SpeedChange");
    }
    [[nodiscard]] bool getRestroreAfterDynamicOverlap() const {
        return getBool("RestroreAfterDynamicOverlap");
    }
    [[nodiscard]] int getRespawnSeconds() const {
        return getInt("RespawnSeconds");
    }
    [[nodiscard]] int getCollisionMargin() const {
        return getInt("CollisionMargin");
    }
    [[nodiscard]] std::string getBaseExportName() const {
        return getString("BaseExportName");
    }
    [[nodiscard]] std::string getBaseExplosionEffect() const {
        return getString("BaseExplosionEffect");
    }
    [[nodiscard]] std::string getBaseHitEffect() const {
        return getString("BaseHitEffect");
    }
    [[nodiscard]] std::string getBaseWindEffect() const {
        return getString("BaseWindEffect");
    }
    [[nodiscard]] std::string getBaseBulletHole1() const {
        return getString("BaseBulletHole1");
    }
    [[nodiscard]] std::string getBaseBulletHole2() const {
        return getString("BaseBulletHole2");
    }
    [[nodiscard]] std::string getBaseCrack1() const {
        return getString("BaseCrack1");
    }
    [[nodiscard]] std::string getBaseCrack2() const {
        return getString("BaseCrack2");
    }
    [[nodiscard]] int getSortOffset() const {
        return getInt("SortOffset");
    }
    [[nodiscard]] bool getHasHitAnim() const {
        return getBool("HasHitAnim");
    }
    [[nodiscard]] bool getHasWindAnim() const {
        return getBool("HasWindAnim");
    }
    [[nodiscard]] int getShadowScaleX() const {
        return getInt("ShadowScaleX");
    }
    [[nodiscard]] int getShadowScaleY() const {
        return getInt("ShadowScaleY");
    }
    [[nodiscard]] int getShadowX() const {
        return getInt("ShadowX");
    }
    [[nodiscard]] int getShadowY() const {
        return getInt("ShadowY");
    }
    [[nodiscard]] int getShadowSkew() const {
        return getInt("ShadowSkew");
    }
    [[nodiscard]] int getLifetime() const {
        return getInt("Lifetime");
    }
    [[nodiscard]] std::string getCustomSCW() const {
        return getString("CustomSCW");
    }
    [[nodiscard]] std::string getCustomMesh() const {
        return getString("CustomMesh");
    }
    [[nodiscard]] int getCustomAngleStep() const {
        return getInt("CustomAngleStep");
    }
    [[nodiscard]] bool getMapEditorVisible() const {
        return getBool("MapEditorVisible");
    }
    [[nodiscard]] int getMapEditorVisualMode() const {
        return getInt("MapEditorVisualMode");
    }
    [[nodiscard]] bool getMapEditorConnected() const {
        return getBool("MapEditorConnected");
    }
};

} // namespace titan
