#pragma once

// LogicSeasonalSkinSectionData — typed facade over csv_logic/seasonal_skin_sections.csv (class 56),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicSeasonalSkinSectionData : public LogicData {
public:
    LogicSeasonalSkinSectionData(const DataTables* tables, int row)
        : LogicData(tables, 56, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getMode() const {
        return getInt("Mode");
    }
    [[nodiscard]] std::string getIncludedCampaigns() const {
        return getString("IncludedCampaigns");
    }
    [[nodiscard]] std::string getSectionTitleTID() const {
        return getString("SectionTitleTID");
    }
    [[nodiscard]] std::string getSectionItemTID() const {
        return getString("SectionItemTID");
    }
    [[nodiscard]] std::string getSectionInfoTID() const {
        return getString("SectionInfoTID");
    }
    [[nodiscard]] bool getLastChanceSectionSeparately() const {
        return getBool("LastChanceSectionSeparately");
    }
    [[nodiscard]] std::string getLastChanceSectionTID() const {
        return getString("LastChanceSectionTID");
    }
    [[nodiscard]] bool getGroupCampaign() const {
        return getBool("GroupCampaign");
    }
    [[nodiscard]] std::string getGroupShopItem() const {
        return getString("GroupShopItem");
    }
    [[nodiscard]] std::string getShopItemCharacters() const {
        return getString("ShopItemCharacters");
    }
    [[nodiscard]] bool getCheckDataFromOffers() const {
        return getBool("CheckDataFromOffers");
    }
    [[nodiscard]] std::string getPurchasePopupBg() const {
        return getString("PurchasePopupBg");
    }
};

} // namespace titan
