#pragma once

// LogicLocationThemeData — typed facade over csv_logic/location_themes.csv (class 47),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicLocationThemeData : public LogicData {
public:
    LogicLocationThemeData(const DataTables* tables, int row)
        : LogicData(tables, 47, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getTileSetPrefix() const {
        return getString("TileSetPrefix");
    }
    [[nodiscard]] std::string getBannerSWF() const {
        return getString("BannerSWF");
    }
    [[nodiscard]] std::string getBannerExportName() const {
        return getString("BannerExportName");
    }
    [[nodiscard]] bool getIsland() const {
        return getBool("Island");
    }
    [[nodiscard]] std::string getMusic() const {
        return getString("Music");
    }
    [[nodiscard]] std::string getGroundSCW() const {
        return getString("GroundSCW");
    }
    [[nodiscard]] std::string getEnvironmentSCW() const {
        return getString("EnvironmentSCW");
    }
    [[nodiscard]] std::string getMaskedEnvironmentSCW() const {
        return getString("MaskedEnvironmentSCW");
    }
    [[nodiscard]] std::string getCampaignGroundSCW() const {
        return getString("CampaignGroundSCW");
    }
    [[nodiscard]] std::string getBlocking1SCW() const {
        return getString("Blocking1SCW");
    }
    [[nodiscard]] std::string getBlocking1Mesh() const {
        return getString("Blocking1Mesh");
    }
    [[nodiscard]] int getBlocking1AngleStep() const {
        return getInt("Blocking1AngleStep");
    }
    [[nodiscard]] std::string getBlocking2SCW() const {
        return getString("Blocking2SCW");
    }
    [[nodiscard]] std::string getBlocking2Mesh() const {
        return getString("Blocking2Mesh");
    }
    [[nodiscard]] int getBlocking2AngleStep() const {
        return getInt("Blocking2AngleStep");
    }
    [[nodiscard]] std::string getBlocking3SCW() const {
        return getString("Blocking3SCW");
    }
    [[nodiscard]] std::string getBlocking3Mesh() const {
        return getString("Blocking3Mesh");
    }
    [[nodiscard]] int getBlocking3AngleStep() const {
        return getInt("Blocking3AngleStep");
    }
    [[nodiscard]] std::string getBlocking4SCW() const {
        return getString("Blocking4SCW");
    }
    [[nodiscard]] std::string getBlocking4Mesh() const {
        return getString("Blocking4Mesh");
    }
    [[nodiscard]] int getBlocking4AngleStep() const {
        return getInt("Blocking4AngleStep");
    }
    [[nodiscard]] std::string getRespawningWallSCW() const {
        return getString("RespawningWallSCW");
    }
    [[nodiscard]] std::string getRespawningWallMesh() const {
        return getString("RespawningWallMesh");
    }
    [[nodiscard]] int getRespawningWallAngleStep() const {
        return getInt("RespawningWallAngleStep");
    }
    [[nodiscard]] std::string getRespawningForestSCW() const {
        return getString("RespawningForestSCW");
    }
    [[nodiscard]] std::string getForestSCW() const {
        return getString("ForestSCW");
    }
    [[nodiscard]] std::string getDestructableSCW() const {
        return getString("DestructableSCW");
    }
    [[nodiscard]] std::string getDestructableMesh() const {
        return getString("DestructableMesh");
    }
    [[nodiscard]] int getDestructableAngleStep() const {
        return getInt("DestructableAngleStep");
    }
    [[nodiscard]] std::string getDestructableSCW_CN() const {
        return getString("DestructableSCW_CN");
    }
    [[nodiscard]] std::string getDestructableMesh_CN() const {
        return getString("DestructableMesh_CN");
    }
    [[nodiscard]] int getDestructableAngleStep_CN() const {
        return getInt("DestructableAngleStep_CN");
    }
    [[nodiscard]] std::string getFragileSCW() const {
        return getString("FragileSCW");
    }
    [[nodiscard]] std::string getFragileMesh() const {
        return getString("FragileMesh");
    }
    [[nodiscard]] int getFragileAngleStep() const {
        return getInt("FragileAngleStep");
    }
    [[nodiscard]] std::string getFragileSCW_CN() const {
        return getString("FragileSCW_CN");
    }
    [[nodiscard]] std::string getFragileMesh_CN() const {
        return getString("FragileMesh_CN");
    }
    [[nodiscard]] int getFragileAngleStep_CN() const {
        return getInt("FragileAngleStep_CN");
    }
    [[nodiscard]] std::string getWaterTileSCW() const {
        return getString("WaterTileSCW");
    }
    [[nodiscard]] std::string getFenceSCW() const {
        return getString("FenceSCW");
    }
    [[nodiscard]] std::string getRopeFenceSCW() const {
        return getString("RopeFenceSCW");
    }
    [[nodiscard]] std::string getRoadSCW() const {
        return getString("RoadSCW");
    }
    [[nodiscard]] std::string getIndestructibleSCW() const {
        return getString("IndestructibleSCW");
    }
    [[nodiscard]] std::string getIndestructibleMesh() const {
        return getString("IndestructibleMesh");
    }
    [[nodiscard]] std::string getGroundFillerSCW() const {
        return getString("GroundFillerSCW");
    }
    [[nodiscard]] std::string getLaserBallSkinOverride() const {
        return getString("LaserBallSkinOverride");
    }
    [[nodiscard]] std::string getMineGemSpawnSCWOverride() const {
        return getString("MineGemSpawnSCWOverride");
    }
    [[nodiscard]] std::string getLootBoxSkinOverride() const {
        return getString("LootBoxSkinOverride");
    }
    [[nodiscard]] std::string getSafeSkinOverride() const {
        return getString("SafeSkinOverride");
    }
    [[nodiscard]] std::string getShowdownBoostSCWOverride() const {
        return getString("ShowdownBoostSCWOverride");
    }
    [[nodiscard]] int getMapPreviewBGColorRed() const {
        return getInt("MapPreviewBGColorRed");
    }
    [[nodiscard]] int getMapPreviewBGColorGreen() const {
        return getInt("MapPreviewBGColorGreen");
    }
    [[nodiscard]] int getMapPreviewBGColorBlue() const {
        return getInt("MapPreviewBGColorBlue");
    }
    [[nodiscard]] std::string getMapPreviewGemGrabSpawnHoleExportName() const {
        return getString("MapPreviewGemGrabSpawnHoleExportName");
    }
    [[nodiscard]] std::string getMapPreviewBallExportName() const {
        return getString("MapPreviewBallExportName");
    }
    [[nodiscard]] std::string getMapPreviewGoal1ExportName() const {
        return getString("MapPreviewGoal1ExportName");
    }
    [[nodiscard]] std::string getMapPreviewGoal2ExportName() const {
        return getString("MapPreviewGoal2ExportName");
    }
    [[nodiscard]] std::string getMapPreviewSafeExportName() const {
        return getString("MapPreviewSafeExportName");
    }
    [[nodiscard]] std::string getMapPreviewCNOverrides() const {
        return getString("MapPreviewCNOverrides");
    }
    [[nodiscard]] int getMapWidth() const {
        return getInt("MapWidth");
    }
    [[nodiscard]] int getMapHeight() const {
        return getInt("MapHeight");
    }
};

} // namespace titan
