#pragma once

// LogicRankedLocationData — typed facade over csv_logic/ranked_locations.csv (class 59),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicRankedLocationData : public LogicData {
public:
    LogicRankedLocationData(const DataTables* tables, int row)
        : LogicData(tables, 59, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
};

} // namespace titan
