#pragma once

// LogicCarryableData — typed facade over csv_logic/carryables.csv (class 60),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicCarryableData : public LogicData {
public:
    LogicCarryableData(const DataTables* tables, int row)
        : LogicData(tables, 60, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getThrowOverWalls() const {
        return getBool("ThrowOverWalls");
    }
    [[nodiscard]] bool getThrowFromGroundLevel() const {
        return getBool("ThrowFromGroundLevel");
    }
    [[nodiscard]] int getMaxZ() const {
        return getInt("MaxZ");
    }
    [[nodiscard]] std::string getThrowSkill() const {
        return getString("ThrowSkill");
    }
    [[nodiscard]] std::string getThrowSkillUlti() const {
        return getString("ThrowSkillUlti");
    }
    [[nodiscard]] bool getShouldRoll() const {
        return getBool("ShouldRoll");
    }
    [[nodiscard]] bool getBouncing() const {
        return getBool("Bouncing");
    }
    [[nodiscard]] int getMinScale() const {
        return getInt("MinScale");
    }
    [[nodiscard]] int getMaxScale() const {
        return getInt("MaxScale");
    }
    [[nodiscard]] bool getShowTeamCircle() const {
        return getBool("ShowTeamCircle");
    }
    [[nodiscard]] bool getAllowOwnTeamPickup() const {
        return getBool("AllowOwnTeamPickup");
    }
    [[nodiscard]] bool getPreventPickupInTargetBase() const {
        return getBool("PreventPickupInTargetBase");
    }
    [[nodiscard]] bool getPreventPickupFromLastTouchingTeam() const {
        return getBool("PreventPickupFromLastTouchingTeam");
    }
    [[nodiscard]] bool getThrowOnTouch() const {
        return getBool("ThrowOnTouch");
    }
    [[nodiscard]] int getMinHeightForGrab() const {
        return getInt("MinHeightForGrab");
    }
};

} // namespace titan
