#pragma once

// LogicTutorialStepData — typed facade over csv_client/tutorial.csv (class 26),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicTutorialStepData : public LogicData {
public:
    LogicTutorialStepData(const DataTables* tables, int row)
        : LogicData(tables, 26, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getStepName() const {
        return getString("StepName");
    }
    [[nodiscard]] int getStartDelayMS() const {
        return getInt("StartDelayMS");
    }
    [[nodiscard]] int getEndDelayMS() const {
        return getInt("EndDelayMS");
    }
    [[nodiscard]] int getForceSpeechBubbleCloseMS() const {
        return getInt("ForceSpeechBubbleCloseMS");
    }
    [[nodiscard]] std::string getStartCondition() const {
        return getString("StartCondition");
    }
    [[nodiscard]] int getStartLocationX() const {
        return getInt("StartLocationX");
    }
    [[nodiscard]] int getStartLocationY() const {
        return getInt("StartLocationY");
    }
    [[nodiscard]] int getStartLocationRadius() const {
        return getInt("StartLocationRadius");
    }
    [[nodiscard]] int getAnimationX() const {
        return getInt("AnimationX");
    }
    [[nodiscard]] int getAnimationY() const {
        return getInt("AnimationY");
    }
    [[nodiscard]] int getAnimationX2() const {
        return getInt("AnimationX2");
    }
    [[nodiscard]] int getAnimationY2() const {
        return getInt("AnimationY2");
    }
    [[nodiscard]] std::string getCompleteCondition() const {
        return getString("CompleteCondition");
    }
    [[nodiscard]] bool getShouldUseAutoShoot() const {
        return getBool("ShouldUseAutoShoot");
    }
    [[nodiscard]] int getCompleteLocationX() const {
        return getInt("CompleteLocationX");
    }
    [[nodiscard]] int getCompleteLocationY() const {
        return getInt("CompleteLocationY");
    }
    [[nodiscard]] int getCompleteLocationRadius() const {
        return getInt("CompleteLocationRadius");
    }
    [[nodiscard]] int getUseUltiX() const {
        return getInt("UseUltiX");
    }
    [[nodiscard]] int getUseUltiY() const {
        return getInt("UseUltiY");
    }
    [[nodiscard]] std::string getAnimationClipSWF() const {
        return getString("AnimationClipSWF");
    }
    [[nodiscard]] std::string getAnimationMovieClip() const {
        return getString("AnimationMovieClip");
    }
    [[nodiscard]] std::string getAnimationClipSWF2() const {
        return getString("AnimationClipSWF2");
    }
    [[nodiscard]] std::string getAnimationMovieClip2() const {
        return getString("AnimationMovieClip2");
    }
    [[nodiscard]] std::string getSpeechBubbleCharacterSWF() const {
        return getString("SpeechBubbleCharacterSWF");
    }
    [[nodiscard]] std::string getSpeechBubbleCharacterMovieClip() const {
        return getString("SpeechBubbleCharacterMovieClip");
    }
    [[nodiscard]] std::string getSpeechBubbleTIDs() const {
        return getString("SpeechBubbleTIDs");
    }
    [[nodiscard]] std::string getStartSound() const {
        return getString("StartSound");
    }
    [[nodiscard]] std::string getSpawnCharacter() const {
        return getString("SpawnCharacter");
    }
    [[nodiscard]] int getSpawnLocationX() const {
        return getInt("SpawnLocationX");
    }
    [[nodiscard]] int getSpawnLocationY() const {
        return getInt("SpawnLocationY");
    }
    [[nodiscard]] int getCustomData() const {
        return getInt("CustomData");
    }
    [[nodiscard]] bool getBlockingSpeechBubble() const {
        return getBool("BlockingSpeechBubble");
    }
    [[nodiscard]] bool getShowUlti() const {
        return getBool("ShowUlti");
    }
    [[nodiscard]] bool getShowShootStick() const {
        return getBool("ShowShootStick");
    }
    [[nodiscard]] bool getLeftSpeechBubble() const {
        return getBool("LeftSpeechBubble");
    }
};

} // namespace titan
