#pragma once

// LogicAllianceBadgeData — typed facade over csv_logic/alliance_badges.csv (class 8),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicAllianceBadgeData : public LogicData {
public:
    LogicAllianceBadgeData(const DataTables* tables, int row)
        : LogicData(tables, 8, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] std::string getCategory() const {
        return getString("Category");
    }
};

} // namespace titan
