#pragma once

// LogicRankedRankData — typed facade over csv_logic/ranked_ranks.csv (class 58),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicRankedRankData : public LogicData {
public:
    LogicRankedRankData(const DataTables* tables, int row)
        : LogicData(tables, 58, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getRank() const {
        return getInt("Rank");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getHexColor() const {
        return getString("HexColor");
    }
    [[nodiscard]] std::string getFrameLabel() const {
        return getString("FrameLabel");
    }
    [[nodiscard]] std::string getRankIconTextField() const {
        return getString("RankIconTextField");
    }
    [[nodiscard]] std::string getRankIconTID() const {
        return getString("RankIconTID");
    }
};

} // namespace titan
