#pragma once

// LogicColorGradientData — typed facade over csv_client/color_gradients.csv (class 46),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicColorGradientData : public LogicData {
public:
    LogicColorGradientData(const DataTables* tables, int row)
        : LogicData(tables, 46, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getColors() const {
        return getString("Colors");
    }
    [[nodiscard]] int getSpeed() const {
        return getInt("Speed");
    }
    [[nodiscard]] int getScale() const {
        return getInt("Scale");
    }
};

} // namespace titan
