#pragma once

// LogicAnimationData — typed facade over csv_client/animations.csv (class 24),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicAnimationData : public LogicData {
public:
    LogicAnimationData(const DataTables* tables, int row)
        : LogicData(tables, 24, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] int getStartFrame() const {
        return getInt("StartFrame");
    }
    [[nodiscard]] int getEndFrame() const {
        return getInt("EndFrame");
    }
    [[nodiscard]] int getFaceFreezeFrame() const {
        return getInt("FaceFreezeFrame");
    }
    [[nodiscard]] int getSpeed() const {
        return getInt("Speed");
    }
    [[nodiscard]] int getTransitionInMs() const {
        return getInt("TransitionInMs");
    }
    [[nodiscard]] int getTransitionOutMs() const {
        return getInt("TransitionOutMs");
    }
    [[nodiscard]] int getAutoFadeMs() const {
        return getInt("AutoFadeMs");
    }
    [[nodiscard]] bool getLooping() const {
        return getBool("Looping");
    }
    [[nodiscard]] std::string getPriority() const {
        return getString("Priority");
    }
};

} // namespace titan
