#pragma once

// LogicCreditsData — typed facade over csv_client/credits.csv (class 13),
// generated by tools/gen_dataclasses.py from the CSV header.
  // REVIEW: class name derived, no binary C2 symbol found.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicCreditsData : public LogicData {
public:
    LogicCreditsData(const DataTables* tables, int row)
        : LogicData(tables, 13, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getC0() const {
        return getInt("0");
    }
};

} // namespace titan
