#pragma once

// LogicPlayerMapEnvironmentData — typed facade over csv_logic/player_map_environments.csv (class 54),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicPlayerMapEnvironmentData : public LogicData {
public:
    LogicPlayerMapEnvironmentData(const DataTables* tables, int row)
        : LogicData(tables, 54, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getGameModeVariations() const {
        return getString("GameModeVariations");
    }
    [[nodiscard]] std::string getLocationThemes() const {
        return getString("LocationThemes");
    }
    [[nodiscard]] std::string getMapTemplates() const {
        return getString("MapTemplates");
    }
};

} // namespace titan
