#pragma once

// LogicNameColorData — typed facade over csv_logic/name_colors.csv (class 43),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicNameColorData : public LogicData {
public:
    LogicNameColorData(const DataTables* tables, int row)
        : LogicData(tables, 43, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getColorCode() const {
        return getString("ColorCode");
    }
    [[nodiscard]] std::string getGradient() const {
        return getString("Gradient");
    }
    [[nodiscard]] int getRequiredExpLevel() const {
        return getInt("RequiredExpLevel");
    }
    [[nodiscard]] int getRequiredTotalTrophies() const {
        return getInt("RequiredTotalTrophies");
    }
    [[nodiscard]] int getRequiredSeasonPoints() const {
        return getInt("RequiredSeasonPoints");
    }
    [[nodiscard]] std::string getRequiredHero() const {
        return getString("RequiredHero");
    }
    [[nodiscard]] int getSortOrder() const {
        return getInt("SortOrder");
    }
    [[nodiscard]] std::string getColorGradient() const {
        return getString("ColorGradient");
    }
};

} // namespace titan
