#pragma once

// LogicSkinConfData — typed facade over csv_logic/skin_confs.csv (class 44),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicSkinConfData : public LogicData {
public:
    LogicSkinConfData(const DataTables* tables, int row)
        : LogicData(tables, 44, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getCharacter() const {
        return getString("Character");
    }
    [[nodiscard]] std::string getModel() const {
        return getString("Model");
    }
    [[nodiscard]] std::string getModelCNOverride() const {
        return getString("ModelCNOverride");
    }
    [[nodiscard]] std::string getGadgetModel() const {
        return getString("GadgetModel");
    }
    [[nodiscard]] std::string getPortraitCameraFile() const {
        return getString("PortraitCameraFile");
    }
    [[nodiscard]] std::string getIntroCameraFile() const {
        return getString("IntroCameraFile");
    }
    [[nodiscard]] bool getMirrorIntro() const {
        return getBool("MirrorIntro");
    }
    [[nodiscard]] std::string getIdleAnim() const {
        return getString("IdleAnim");
    }
    [[nodiscard]] std::string getWalkAnim() const {
        return getString("WalkAnim");
    }
    [[nodiscard]] std::string getPrimarySkillAnim() const {
        return getString("PrimarySkillAnim");
    }
    [[nodiscard]] std::string getSecondarySkillAnim() const {
        return getString("SecondarySkillAnim");
    }
    [[nodiscard]] std::string getPrimarySkillRecoilAnim() const {
        return getString("PrimarySkillRecoilAnim");
    }
    [[nodiscard]] std::string getPrimarySkillRecoilAnim2() const {
        return getString("PrimarySkillRecoilAnim2");
    }
    [[nodiscard]] std::string getSecondarySkillRecoilAnim() const {
        return getString("SecondarySkillRecoilAnim");
    }
    [[nodiscard]] std::string getSecondarySkillRecoilAnim2() const {
        return getString("SecondarySkillRecoilAnim2");
    }
    [[nodiscard]] std::string getReloadingAnim() const {
        return getString("ReloadingAnim");
    }
    [[nodiscard]] std::string getPushbackAnim() const {
        return getString("PushbackAnim");
    }
    [[nodiscard]] std::string getHappyAnim() const {
        return getString("HappyAnim");
    }
    [[nodiscard]] std::string getHappyLoopAnim() const {
        return getString("HappyLoopAnim");
    }
    [[nodiscard]] std::string getSadAnim() const {
        return getString("SadAnim");
    }
    [[nodiscard]] std::string getSadLoopAnim() const {
        return getString("SadLoopAnim");
    }
    [[nodiscard]] std::string getLobbyAnim() const {
        return getString("LobbyAnim");
    }
    [[nodiscard]] std::string getLobbyLoopAnim() const {
        return getString("LobbyLoopAnim");
    }
    [[nodiscard]] std::string getHeroScreenIdleAnim() const {
        return getString("HeroScreenIdleAnim");
    }
    [[nodiscard]] std::string getHeroScreenAnim() const {
        return getString("HeroScreenAnim");
    }
    [[nodiscard]] std::string getHeroScreenLoopAnim() const {
        return getString("HeroScreenLoopAnim");
    }
    [[nodiscard]] std::string getSignatureAnim() const {
        return getString("SignatureAnim");
    }
    [[nodiscard]] std::string getHappyEnterAnim() const {
        return getString("HappyEnterAnim");
    }
    [[nodiscard]] std::string getSadEnterAnim() const {
        return getString("SadEnterAnim");
    }
    [[nodiscard]] std::string getProfileAnim() const {
        return getString("ProfileAnim");
    }
    [[nodiscard]] std::string getIntroAnim() const {
        return getString("IntroAnim");
    }
    [[nodiscard]] std::string getEnvAnim() const {
        return getString("EnvAnim");
    }
    [[nodiscard]] std::string getBossAutoAttackAnim() const {
        return getString("BossAutoAttackAnim");
    }
    [[nodiscard]] std::string getBossAutoAttackRecoilAnim() const {
        return getString("BossAutoAttackRecoilAnim");
    }
    [[nodiscard]] std::string getBossAutoAttackRecoilAnim2() const {
        return getString("BossAutoAttackRecoilAnim2");
    }
    [[nodiscard]] std::string getGadgetActiveAnim() const {
        return getString("GadgetActiveAnim");
    }
    [[nodiscard]] std::string getGadgetRecoilAnim() const {
        return getString("GadgetRecoilAnim");
    }
    [[nodiscard]] std::string getIdleFace() const {
        return getString("IdleFace");
    }
    [[nodiscard]] std::string getWalkFace() const {
        return getString("WalkFace");
    }
    [[nodiscard]] std::string getHappyFace() const {
        return getString("HappyFace");
    }
    [[nodiscard]] std::string getHappyLoopFace() const {
        return getString("HappyLoopFace");
    }
    [[nodiscard]] std::string getSadFace() const {
        return getString("SadFace");
    }
    [[nodiscard]] std::string getSadLoopFace() const {
        return getString("SadLoopFace");
    }
    [[nodiscard]] std::string getLobbyFace() const {
        return getString("LobbyFace");
    }
    [[nodiscard]] std::string getLobbyLoopFace() const {
        return getString("LobbyLoopFace");
    }
    [[nodiscard]] std::string getHeroScreenIdleFace() const {
        return getString("HeroScreenIdleFace");
    }
    [[nodiscard]] std::string getHeroScreenFace() const {
        return getString("HeroScreenFace");
    }
    [[nodiscard]] std::string getHeroScreenLoopFace() const {
        return getString("HeroScreenLoopFace");
    }
    [[nodiscard]] std::string getSignatureFace() const {
        return getString("SignatureFace");
    }
    [[nodiscard]] std::string getProfileFace() const {
        return getString("ProfileFace");
    }
    [[nodiscard]] std::string getIntroFace() const {
        return getString("IntroFace");
    }
    [[nodiscard]] std::string getLobbyEffect() const {
        return getString("LobbyEffect");
    }
    [[nodiscard]] std::string getHeroScreenEffect() const {
        return getString("HeroScreenEffect");
    }
    [[nodiscard]] std::string getSignatureEffect() const {
        return getString("SignatureEffect");
    }
    [[nodiscard]] std::string getHappyEffect() const {
        return getString("HappyEffect");
    }
    [[nodiscard]] std::string getSadEffect() const {
        return getString("SadEffect");
    }
    [[nodiscard]] bool getPetInSameSprite() const {
        return getBool("PetInSameSprite");
    }
    [[nodiscard]] bool getAttackLocksAttackAngle() const {
        return getBool("AttackLocksAttackAngle");
    }
    [[nodiscard]] bool getUltiLocksAttackAngle() const {
        return getBool("UltiLocksAttackAngle");
    }
    [[nodiscard]] std::string getMainAttackProjectile() const {
        return getString("MainAttackProjectile");
    }
    [[nodiscard]] std::string getSecondaryProjectile() const {
        return getString("SecondaryProjectile");
    }
    [[nodiscard]] std::string getUltiProjectile() const {
        return getString("UltiProjectile");
    }
    [[nodiscard]] std::string getMainAttackEffect() const {
        return getString("MainAttackEffect");
    }
    [[nodiscard]] std::string getMainAttackEffect2() const {
        return getString("MainAttackEffect2");
    }
    [[nodiscard]] std::string getUltiAttackEffect() const {
        return getString("UltiAttackEffect");
    }
    [[nodiscard]] std::string getUltiAttackEffect2() const {
        return getString("UltiAttackEffect2");
    }
    [[nodiscard]] bool getUseBlueTextureInMenus() const {
        return getBool("UseBlueTextureInMenus");
    }
    [[nodiscard]] std::string getMainAttackUseEffect() const {
        return getString("MainAttackUseEffect");
    }
    [[nodiscard]] std::string getUltiUseEffect() const {
        return getString("UltiUseEffect");
    }
    [[nodiscard]] std::string getUltiEndEffect() const {
        return getString("UltiEndEffect");
    }
    [[nodiscard]] std::string getMeleeHitEffect() const {
        return getString("MeleeHitEffect");
    }
    [[nodiscard]] std::string getSpawnEffect() const {
        return getString("SpawnEffect");
    }
    [[nodiscard]] std::string getReloadEffect() const {
        return getString("ReloadEffect");
    }
    [[nodiscard]] std::string getUltiLoopEffect() const {
        return getString("UltiLoopEffect");
    }
    [[nodiscard]] std::string getUltiLoopEffect2() const {
        return getString("UltiLoopEffect2");
    }
    [[nodiscard]] std::string getStarPower1Effect() const {
        return getString("StarPower1Effect");
    }
    [[nodiscard]] std::string getStarPower2Effect() const {
        return getString("StarPower2Effect");
    }
    [[nodiscard]] std::string getAreaEffect() const {
        return getString("AreaEffect");
    }
    [[nodiscard]] std::string getAreaEffectStarPower() const {
        return getString("AreaEffectStarPower");
    }
    [[nodiscard]] std::string getAreaEffectStarPower2() const {
        return getString("AreaEffectStarPower2");
    }
    [[nodiscard]] std::string getAreaEffectAttack() const {
        return getString("AreaEffectAttack");
    }
    [[nodiscard]] std::string getAreaEffectUlti() const {
        return getString("AreaEffectUlti");
    }
    [[nodiscard]] std::string getSpawnedItem() const {
        return getString("SpawnedItem");
    }
    [[nodiscard]] std::string getKillCelebrationSoundVO() const {
        return getString("KillCelebrationSoundVO");
    }
    [[nodiscard]] std::string getInLeadCelebrationSoundVO() const {
        return getString("InLeadCelebrationSoundVO");
    }
    [[nodiscard]] std::string getStartSoundVO() const {
        return getString("StartSoundVO");
    }
    [[nodiscard]] std::string getUseUltiSoundVO() const {
        return getString("UseUltiSoundVO");
    }
    [[nodiscard]] std::string getTakeDamageSoundVO() const {
        return getString("TakeDamageSoundVO");
    }
    [[nodiscard]] std::string getDeathSoundVO() const {
        return getString("DeathSoundVO");
    }
    [[nodiscard]] std::string getAttackSoundVO() const {
        return getString("AttackSoundVO");
    }
    [[nodiscard]] std::string getUnlockVO() const {
        return getString("UnlockVO");
    }
    [[nodiscard]] int getUnlockVOIndex() const {
        return getInt("UnlockVOIndex");
    }
    [[nodiscard]] std::string getBoneEffect1() const {
        return getString("BoneEffect1");
    }
    [[nodiscard]] std::string getBoneEffect2() const {
        return getString("BoneEffect2");
    }
    [[nodiscard]] std::string getBoneEffect3() const {
        return getString("BoneEffect3");
    }
    [[nodiscard]] std::string getBoneEffect4() const {
        return getString("BoneEffect4");
    }
    [[nodiscard]] std::string getBoneEffectUse() const {
        return getString("BoneEffectUse");
    }
    [[nodiscard]] std::string getAutoAttackProjectile() const {
        return getString("AutoAttackProjectile");
    }
    [[nodiscard]] std::string getProjectileForShockyStarPower() const {
        return getString("ProjectileForShockyStarPower");
    }
    [[nodiscard]] std::string getIncendiaryStarPowerAreaEffect() const {
        return getString("IncendiaryStarPowerAreaEffect");
    }
    [[nodiscard]] std::string getMoveEffect() const {
        return getString("MoveEffect");
    }
    [[nodiscard]] std::string getMoveEffect2() const {
        return getString("MoveEffect2");
    }
    [[nodiscard]] std::string getChargeMoveEffect() const {
        return getString("ChargeMoveEffect");
    }
    [[nodiscard]] std::string getStillEffect() const {
        return getString("StillEffect");
    }
    [[nodiscard]] std::string getStillEffect2() const {
        return getString("StillEffect2");
    }
    [[nodiscard]] std::string getChargedShotEffect() const {
        return getString("ChargedShotEffect");
    }
    [[nodiscard]] bool getDisableHeadRotation() const {
        return getBool("DisableHeadRotation");
    }
};

} // namespace titan
