#pragma once

// LogicThemeData — typed facade over csv_logic/themes.csv (class 41),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicThemeData : public LogicData {
public:
    LogicThemeData(const DataTables* tables, int row)
        : LogicData(tables, 41, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
    [[nodiscard]] std::string getParticleFileName() const {
        return getString("ParticleFileName");
    }
    [[nodiscard]] std::string getParticleExportName() const {
        return getString("ParticleExportName");
    }
    [[nodiscard]] std::string getParticleStyle() const {
        return getString("ParticleStyle");
    }
    [[nodiscard]] int getParticleVariations() const {
        return getInt("ParticleVariations");
    }
    [[nodiscard]] std::string getThemeMusic() const {
        return getString("ThemeMusic");
    }
    [[nodiscard]] bool getUseInLevelSelection() const {
        return getBool("UseInLevelSelection");
    }
};

} // namespace titan
