#pragma once

// LogicEmoteBundleData — typed facade over csv_logic/emote_bundles.csv (class 53),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicEmoteBundleData : public LogicData {
public:
    LogicEmoteBundleData(const DataTables* tables, int row)
        : LogicData(tables, 53, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] bool getCanBeBought() const {
        return getBool("CanBeBought");
    }
};

} // namespace titan
