#pragma once

// LogicCharacterData — typed facade over csv_logic/characters.csv (class 16),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicCharacterData : public LogicData {
public:
    LogicCharacterData(const DataTables* tables, int row)
        : LogicData(tables, 16, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] bool getLockedForChronos() const {
        return getBool("LockedForChronos");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] std::string getItemName() const {
        return getString("ItemName");
    }
    [[nodiscard]] std::string getWeaponSkill() const {
        return getString("WeaponSkill");
    }
    [[nodiscard]] std::string getUltimateSkill() const {
        return getString("UltimateSkill");
    }
    [[nodiscard]] std::string getPet() const {
        return getString("Pet");
    }
    [[nodiscard]] int getSpeed() const {
        return getInt("Speed");
    }
    [[nodiscard]] int getHitpoints() const {
        return getInt("Hitpoints");
    }
    [[nodiscard]] int getSelfDamagePerSecond() const {
        return getInt("SelfDamagePerSecond");
    }
    [[nodiscard]] bool getMeleeAutoAttackSplashDamage() const {
        return getBool("MeleeAutoAttackSplashDamage");
    }
    [[nodiscard]] int getAutoAttackSpeedMs() const {
        return getInt("AutoAttackSpeedMs");
    }
    [[nodiscard]] int getAutoAttackDamage() const {
        return getInt("AutoAttackDamage");
    }
    [[nodiscard]] int getAutoAttackBulletsPerShot() const {
        return getInt("AutoAttackBulletsPerShot");
    }
    [[nodiscard]] std::string getAutoAttackMode() const {
        return getString("AutoAttackMode");
    }
    [[nodiscard]] int getAutoAttackProjectileSpread() const {
        return getInt("AutoAttackProjectileSpread");
    }
    [[nodiscard]] std::string getAutoAttackProjectile() const {
        return getString("AutoAttackProjectile");
    }
    [[nodiscard]] int getAutoAttackRange() const {
        return getInt("AutoAttackRange");
    }
    [[nodiscard]] int getRegeneratePerSecond() const {
        return getInt("RegeneratePerSecond");
    }
    [[nodiscard]] bool getLowPriorityTarget() const {
        return getBool("LowPriorityTarget");
    }
    [[nodiscard]] int getUltiChargeMul() const {
        return getInt("UltiChargeMul");
    }
    [[nodiscard]] int getUltiChargeUltiMul() const {
        return getInt("UltiChargeUltiMul");
    }
    [[nodiscard]] std::string getType() const {
        return getString("Type");
    }
    [[nodiscard]] std::string getCarryableType() const {
        return getString("CarryableType");
    }
    [[nodiscard]] int getDamagerPercentFromAliens() const {
        return getInt("DamagerPercentFromAliens");
    }
    [[nodiscard]] std::string getDefaultSkin() const {
        return getString("DefaultSkin");
    }
    [[nodiscard]] bool getManualRotations() const {
        return getBool("ManualRotations");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getBlueExportName() const {
        return getString("BlueExportName");
    }
    [[nodiscard]] std::string getRedExportName() const {
        return getString("RedExportName");
    }
    [[nodiscard]] std::string getShadowExportName() const {
        return getString("ShadowExportName");
    }
    [[nodiscard]] std::string getAreaEffect() const {
        return getString("AreaEffect");
    }
    [[nodiscard]] std::string getDeathAreaEffect() const {
        return getString("DeathAreaEffect");
    }
    [[nodiscard]] std::string getTakeDamageEffect() const {
        return getString("TakeDamageEffect");
    }
    [[nodiscard]] std::string getDeathEffect() const {
        return getString("DeathEffect");
    }
    [[nodiscard]] std::string getMoveEffect() const {
        return getString("MoveEffect");
    }
    [[nodiscard]] std::string getReloadEffect() const {
        return getString("ReloadEffect");
    }
    [[nodiscard]] std::string getOutOfAmmoEffect() const {
        return getString("OutOfAmmoEffect");
    }
    [[nodiscard]] std::string getDryFireEffect() const {
        return getString("DryFireEffect");
    }
    [[nodiscard]] std::string getSpawnEffect() const {
        return getString("SpawnEffect");
    }
    [[nodiscard]] std::string getMeleeHitEffect() const {
        return getString("MeleeHitEffect");
    }
    [[nodiscard]] std::string getAutoAttackStartEffect() const {
        return getString("AutoAttackStartEffect");
    }
    [[nodiscard]] std::string getBoneEffect1() const {
        return getString("BoneEffect1");
    }
    [[nodiscard]] std::string getBoneEffect2() const {
        return getString("BoneEffect2");
    }
    [[nodiscard]] std::string getBoneEffect3() const {
        return getString("BoneEffect3");
    }
    [[nodiscard]] std::string getBoneEffect4() const {
        return getString("BoneEffect4");
    }
    [[nodiscard]] std::string getBoneEffectUse() const {
        return getString("BoneEffectUse");
    }
    [[nodiscard]] std::string getLoopedEffect() const {
        return getString("LoopedEffect");
    }
    [[nodiscard]] std::string getLoopedEffect2() const {
        return getString("LoopedEffect2");
    }
    [[nodiscard]] std::string getKillCelebrationSoundVO() const {
        return getString("KillCelebrationSoundVO");
    }
    [[nodiscard]] std::string getInLeadCelebrationSoundVO() const {
        return getString("InLeadCelebrationSoundVO");
    }
    [[nodiscard]] std::string getStartSoundVO() const {
        return getString("StartSoundVO");
    }
    [[nodiscard]] std::string getUseUltiSoundVO() const {
        return getString("UseUltiSoundVO");
    }
    [[nodiscard]] std::string getTakeDamageSoundVO() const {
        return getString("TakeDamageSoundVO");
    }
    [[nodiscard]] std::string getDeathSoundVO() const {
        return getString("DeathSoundVO");
    }
    [[nodiscard]] std::string getAttackSoundVO() const {
        return getString("AttackSoundVO");
    }
    [[nodiscard]] std::string getUnlockVO() const {
        return getString("UnlockVO");
    }
    [[nodiscard]] int getUnlockVOIndex() const {
        return getInt("UnlockVOIndex");
    }
    [[nodiscard]] int getAttackStartEffectOffset() const {
        return getInt("AttackStartEffectOffset");
    }
    [[nodiscard]] int getTwoWeaponAttackEffectOffset() const {
        return getInt("TwoWeaponAttackEffectOffset");
    }
    [[nodiscard]] int getShadowScaleX() const {
        return getInt("ShadowScaleX");
    }
    [[nodiscard]] int getShadowScaleY() const {
        return getInt("ShadowScaleY");
    }
    [[nodiscard]] int getShadowX() const {
        return getInt("ShadowX");
    }
    [[nodiscard]] int getShadowY() const {
        return getInt("ShadowY");
    }
    [[nodiscard]] int getShadowSkew() const {
        return getInt("ShadowSkew");
    }
    [[nodiscard]] int getScale() const {
        return getInt("Scale");
    }
    [[nodiscard]] int getHeroScreenScale() const {
        return getInt("HeroScreenScale");
    }
    [[nodiscard]] int getFitToBoxScale() const {
        return getInt("FitToBoxScale");
    }
    [[nodiscard]] int getEndScreenScale() const {
        return getInt("EndScreenScale");
    }
    [[nodiscard]] int getGatchaScreenScale() const {
        return getInt("GatchaScreenScale");
    }
    [[nodiscard]] int getHomeScreenScale() const {
        return getInt("HomeScreenScale");
    }
    [[nodiscard]] bool getShowPetInHeroScreen() const {
        return getBool("ShowPetInHeroScreen");
    }
    [[nodiscard]] int getHeroScreenXOffset() const {
        return getInt("HeroScreenXOffset");
    }
    [[nodiscard]] int getHeroScreenZOffset() const {
        return getInt("HeroScreenZOffset");
    }
    [[nodiscard]] int getHeroScreenEmoteX() const {
        return getInt("HeroScreenEmoteX");
    }
    [[nodiscard]] int getHeroScreenEmoteY() const {
        return getInt("HeroScreenEmoteY");
    }
    [[nodiscard]] int getCollisionRadius() const {
        return getInt("CollisionRadius");
    }
    [[nodiscard]] std::string getHealthBar() const {
        return getString("HealthBar");
    }
    [[nodiscard]] int getHealthBarOffsetY() const {
        return getInt("HealthBarOffsetY");
    }
    [[nodiscard]] int getFlyingHeight() const {
        return getInt("FlyingHeight");
    }
    [[nodiscard]] int getProjectileStartZ() const {
        return getInt("ProjectileStartZ");
    }
    [[nodiscard]] int getStopMovementAfterMS() const {
        return getInt("StopMovementAfterMS");
    }
    [[nodiscard]] int getWaitMS() const {
        return getInt("WaitMS");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] bool getForceAttackAnimationToEnd() const {
        return getBool("ForceAttackAnimationToEnd");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] int getRecoilAmount() const {
        return getInt("RecoilAmount");
    }
    [[nodiscard]] std::string getHomeworld() const {
        return getString("Homeworld");
    }
    [[nodiscard]] std::string getFootstepClip() const {
        return getString("FootstepClip");
    }
    [[nodiscard]] int getDifferentFootstepOffset() const {
        return getInt("DifferentFootstepOffset");
    }
    [[nodiscard]] int getFootstepIntervalMS() const {
        return getInt("FootstepIntervalMS");
    }
    [[nodiscard]] int getAttackingWeaponScale() const {
        return getInt("AttackingWeaponScale");
    }
    [[nodiscard]] bool getUseThrowingLeftWeaponBoneScaling() const {
        return getBool("UseThrowingLeftWeaponBoneScaling");
    }
    [[nodiscard]] bool getUseThrowingRightWeaponBoneScaling() const {
        return getBool("UseThrowingRightWeaponBoneScaling");
    }
    [[nodiscard]] int getCommonSetUpgradeBonus() const {
        return getInt("CommonSetUpgradeBonus");
    }
    [[nodiscard]] int getRareSetUpgradeBonus() const {
        return getInt("RareSetUpgradeBonus");
    }
    [[nodiscard]] int getSuperRareSetUpgradeBonus() const {
        return getInt("SuperRareSetUpgradeBonus");
    }
    [[nodiscard]] bool getCanWalkOverWater() const {
        return getBool("CanWalkOverWater");
    }
    [[nodiscard]] bool getUseColorMod() const {
        return getBool("UseColorMod");
    }
    [[nodiscard]] int getRedAdd() const {
        return getInt("RedAdd");
    }
    [[nodiscard]] int getGreenAdd() const {
        return getInt("GreenAdd");
    }
    [[nodiscard]] int getBlueAdd() const {
        return getInt("BlueAdd");
    }
    [[nodiscard]] int getRedMul() const {
        return getInt("RedMul");
    }
    [[nodiscard]] int getGreenMul() const {
        return getInt("GreenMul");
    }
    [[nodiscard]] int getBlueMul() const {
        return getInt("BlueMul");
    }
    [[nodiscard]] int getChargeUltiAutomatically() const {
        return getInt("ChargeUltiAutomatically");
    }
    [[nodiscard]] int getChargeUltiFromDamage() const {
        return getInt("ChargeUltiFromDamage");
    }
    [[nodiscard]] std::string getVideoLink() const {
        return getString("VideoLink");
    }
    [[nodiscard]] bool getShouldEncodePetStatus() const {
        return getBool("ShouldEncodePetStatus");
    }
    [[nodiscard]] bool getSecondaryPet() const {
        return getBool("SecondaryPet");
    }
    [[nodiscard]] int getExtraMinions() const {
        return getInt("ExtraMinions");
    }
    [[nodiscard]] int getPetAutoSpawnDelay() const {
        return getInt("PetAutoSpawnDelay");
    }
    [[nodiscard]] bool getHasPowerLevels() const {
        return getBool("HasPowerLevels");
    }
    [[nodiscard]] int getOffenseRating() const {
        return getInt("OffenseRating");
    }
    [[nodiscard]] int getDefenseRating() const {
        return getInt("DefenseRating");
    }
    [[nodiscard]] int getUtilityRating() const {
        return getInt("UtilityRating");
    }
};

} // namespace titan
