#pragma once

// LogicAreaEffectData — typed facade over csv_logic/area_effects.csv (class 17),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicAreaEffectData : public LogicData {
public:
    LogicAreaEffectData(const DataTables* tables, int row)
        : LogicData(tables, 17, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getParentAreaEffectForSkin() const {
        return getString("ParentAreaEffectForSkin");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getOwnExportName() const {
        return getString("OwnExportName");
    }
    [[nodiscard]] std::string getBlueExportName() const {
        return getString("BlueExportName");
    }
    [[nodiscard]] std::string getRedExportName() const {
        return getString("RedExportName");
    }
    [[nodiscard]] std::string getNeutralExportName() const {
        return getString("NeutralExportName");
    }
    [[nodiscard]] std::string getLayer() const {
        return getString("Layer");
    }
    [[nodiscard]] std::string getExportNameTop() const {
        return getString("ExportNameTop");
    }
    [[nodiscard]] std::string getExportNameTopRed() const {
        return getString("ExportNameTopRed");
    }
    [[nodiscard]] std::string getExportNameObject() const {
        return getString("ExportNameObject");
    }
    [[nodiscard]] std::string getEffect() const {
        return getString("Effect");
    }
    [[nodiscard]] std::string getLoopingEffect() const {
        return getString("LoopingEffect");
    }
    [[nodiscard]] bool getAllowEffectInterrupt() const {
        return getBool("AllowEffectInterrupt");
    }
    [[nodiscard]] int getPlaybackType() const {
        return getInt("PlaybackType");
    }
    [[nodiscard]] int getScale() const {
        return getInt("Scale");
    }
    [[nodiscard]] int getTimeMs() const {
        return getInt("TimeMs");
    }
    [[nodiscard]] int getRadius() const {
        return getInt("Radius");
    }
    [[nodiscard]] int getDamage() const {
        return getInt("Damage");
    }
    [[nodiscard]] int getCustomValue() const {
        return getInt("CustomValue");
    }
    [[nodiscard]] int getCustomValue2() const {
        return getInt("CustomValue2");
    }
    [[nodiscard]] std::string getType() const {
        return getString("Type");
    }
    [[nodiscard]] bool getIsPersonal() const {
        return getBool("IsPersonal");
    }
    [[nodiscard]] std::string getBulletExplosionBullet() const {
        return getString("BulletExplosionBullet");
    }
    [[nodiscard]] int getBulletExplosionBulletDistance() const {
        return getInt("BulletExplosionBulletDistance");
    }
    [[nodiscard]] std::string getBulletExplosionItem() const {
        return getString("BulletExplosionItem");
    }
    [[nodiscard]] int getExpandOnDistance() const {
        return getInt("ExpandOnDistance");
    }
    [[nodiscard]] int getBulletAngleOffset() const {
        return getInt("BulletAngleOffset");
    }
    [[nodiscard]] bool getDestroysEnvironment() const {
        return getBool("DestroysEnvironment");
    }
    [[nodiscard]] int getPushbackStrength() const {
        return getInt("PushbackStrength");
    }
    [[nodiscard]] int getPushbackStrengthSelf() const {
        return getInt("PushbackStrengthSelf");
    }
    [[nodiscard]] int getPushbackDeadzone() const {
        return getInt("PushbackDeadzone");
    }
    [[nodiscard]] bool getCanStopGrapple() const {
        return getBool("CanStopGrapple");
    }
    [[nodiscard]] int getFreezeStrength() const {
        return getInt("FreezeStrength");
    }
    [[nodiscard]] int getFreezeTicks() const {
        return getInt("FreezeTicks");
    }
    [[nodiscard]] bool getShouldShowEvenIfOutsideScreen() const {
        return getBool("ShouldShowEvenIfOutsideScreen");
    }
    [[nodiscard]] int getSameAreaEffectCanNotDamageMs() const {
        return getInt("SameAreaEffectCanNotDamageMs");
    }
    [[nodiscard]] bool getDontShowToEnemy() const {
        return getBool("DontShowToEnemy");
    }
    [[nodiscard]] bool getRequireLineOfSight() const {
        return getBool("RequireLineOfSight");
    }
    [[nodiscard]] std::string getChainAreaEffect() const {
        return getString("ChainAreaEffect");
    }
    [[nodiscard]] int getSkinnedCustomValue() const {
        return getInt("SkinnedCustomValue");
    }
    [[nodiscard]] std::string getSpawnItem() const {
        return getString("SpawnItem");
    }
};

} // namespace titan
