#pragma once

// LogicPlayerThumbnailData — typed facade over csv_logic/player_thumbnails.csv (class 28),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicPlayerThumbnailData : public LogicData {
public:
    LogicPlayerThumbnailData(const DataTables* tables, int row)
        : LogicData(tables, 28, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getRequiredExpLevel() const {
        return getInt("RequiredExpLevel");
    }
    [[nodiscard]] int getRequiredTotalTrophies() const {
        return getInt("RequiredTotalTrophies");
    }
    [[nodiscard]] int getRequiredSeasonPoints() const {
        return getInt("RequiredSeasonPoints");
    }
    [[nodiscard]] std::string getRequiredHero() const {
        return getString("RequiredHero");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] int getSortOrder() const {
        return getInt("SortOrder");
    }
    [[nodiscard]] bool getIsReward() const {
        return getBool("IsReward");
    }
};

} // namespace titan
