#pragma once

// LogicClientGlobalData — typed facade over csv_client/client_globals.csv (class 9),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicClientGlobalData : public LogicData {
public:
    LogicClientGlobalData(const DataTables* tables, int row)
        : LogicData(tables, 9, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getNumberValue() const {
        return getInt("NumberValue");
    }
    [[nodiscard]] bool getBooleanValue() const {
        return getBool("BooleanValue");
    }
    [[nodiscard]] std::string getTextValue() const {
        return getString("TextValue");
    }
    [[nodiscard]] int getNumberArray() const {
        return getInt("NumberArray");
    }
    [[nodiscard]] std::string getStringArray() const {
        return getString("StringArray");
    }
    [[nodiscard]] std::string getAltStringArray() const {
        return getString("AltStringArray");
    }
};

} // namespace titan
