#pragma once

// LogicMapData — typed facade over csv_logic/maps.csv (class 19),
// generated by tools/gen_dataclasses.py from the CSV header.
  // REVIEW: class name derived, no binary C2 symbol found.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicMapData : public LogicData {
public:
    LogicMapData(const DataTables* tables, int row)
        : LogicData(tables, 19, row) {}

    [[nodiscard]] std::string getMap() const {
        return getString("Map");
    }
    [[nodiscard]] std::string getData() const {
        return getString("Data");
    }
    [[nodiscard]] std::string getMetaData() const {
        return getString("MetaData");
    }
};

} // namespace titan
