#pragma once

// LogicMapTemplateData — typed facade over csv_logic/map_templates.csv (class 55),
// generated by tools/gen_dataclasses.py from the CSV header.
  // REVIEW: class name derived, no binary C2 symbol found.

#include "titan/game/data/LogicData.cpp"

#include <string>

namespace titan {

class LogicMapTemplateData : public LogicData {
public:
    LogicMapTemplateData(const DataTables* tables, int row)
        : LogicData(tables, 55, row) {}

    [[nodiscard]] std::string getMap() const {
        return getString("Map");
    }
    [[nodiscard]] std::string getData() const {
        return getString("Data");
    }
    [[nodiscard]] std::string getMetaData() const {
        return getString("MetaData");
    }
};

} // namespace titan
