#pragma once

// LogicAccessoryData — typed facade over csv_logic/accessories.csv (class 50),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicAccessoryData : public LogicData {
public:
    LogicAccessoryData(const DataTables* tables, int row)
        : LogicData(tables, 50, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getType() const {
        return getString("Type");
    }
    [[nodiscard]] int getSubType() const {
        return getInt("SubType");
    }
    [[nodiscard]] int getChargeCount() const {
        return getInt("ChargeCount");
    }
    [[nodiscard]] int getCooldown() const {
        return getInt("Cooldown");
    }
    [[nodiscard]] std::string getUseEffect() const {
        return getString("UseEffect");
    }
    [[nodiscard]] std::string getLoopingEffect() const {
        return getString("LoopingEffect");
    }
    [[nodiscard]] std::string getLoopingEffectPet() const {
        return getString("LoopingEffectPet");
    }
    [[nodiscard]] int getActivationDelay() const {
        return getInt("ActivationDelay");
    }
    [[nodiscard]] int getActiveTicks() const {
        return getInt("ActiveTicks");
    }
    [[nodiscard]] bool getShowCountdown() const {
        return getBool("ShowCountdown");
    }
    [[nodiscard]] bool getStopMovement() const {
        return getBool("StopMovement");
    }
    [[nodiscard]] bool getStopPetForDelay() const {
        return getBool("StopPetForDelay");
    }
    [[nodiscard]] int getAnimationIndex() const {
        return getInt("AnimationIndex");
    }
    [[nodiscard]] bool getSetAttackAngle() const {
        return getBool("SetAttackAngle");
    }
    [[nodiscard]] int getAimGuideType() const {
        return getInt("AimGuideType");
    }
    [[nodiscard]] bool getConsumesAmmo() const {
        return getBool("ConsumesAmmo");
    }
    [[nodiscard]] std::string getAreaEffect() const {
        return getString("AreaEffect");
    }
    [[nodiscard]] std::string getPetAreaEffect() const {
        return getString("PetAreaEffect");
    }
    [[nodiscard]] bool getInterruptsAction() const {
        return getBool("InterruptsAction");
    }
    [[nodiscard]] bool getAllowStunActivation() const {
        return getBool("AllowStunActivation");
    }
    [[nodiscard]] bool getInterruptable() const {
        return getBool("Interruptable");
    }
    [[nodiscard]] int getRequirePetDistance() const {
        return getInt("RequirePetDistance");
    }
    [[nodiscard]] bool getDestroyPet() const {
        return getBool("DestroyPet");
    }
    [[nodiscard]] int getRange() const {
        return getInt("Range");
    }
    [[nodiscard]] bool getRequireEnemyInRange() const {
        return getBool("RequireEnemyInRange");
    }
    [[nodiscard]] bool getTargetFriends() const {
        return getBool("TargetFriends");
    }
    [[nodiscard]] bool getTargetIndirect() const {
        return getBool("TargetIndirect");
    }
    [[nodiscard]] int getShieldPercent() const {
        return getInt("ShieldPercent");
    }
    [[nodiscard]] int getShieldTicks() const {
        return getInt("ShieldTicks");
    }
    [[nodiscard]] int getSpeedBoost() const {
        return getInt("SpeedBoost");
    }
    [[nodiscard]] int getSpeedBoostTicks() const {
        return getInt("SpeedBoostTicks");
    }
    [[nodiscard]] bool getSkipTypeCondition() const {
        return getBool("SkipTypeCondition");
    }
    [[nodiscard]] int getUsableDuringCharge() const {
        return getInt("UsableDuringCharge");
    }
    [[nodiscard]] std::string getCustomObject() const {
        return getString("CustomObject");
    }
    [[nodiscard]] int getCustomValue1() const {
        return getInt("CustomValue1");
    }
    [[nodiscard]] int getCustomValue2() const {
        return getInt("CustomValue2");
    }
    [[nodiscard]] int getCustomValue3() const {
        return getInt("CustomValue3");
    }
    [[nodiscard]] int getCustomValue4() const {
        return getInt("CustomValue4");
    }
    [[nodiscard]] int getCustomValue5() const {
        return getInt("CustomValue5");
    }
    [[nodiscard]] int getCustomValue6() const {
        return getInt("CustomValue6");
    }
    [[nodiscard]] std::string getMissingTargetText() const {
        return getString("MissingTargetText");
    }
    [[nodiscard]] std::string getTargetTooFarText() const {
        return getString("TargetTooFarText");
    }
    [[nodiscard]] std::string getTargetAlreadyActiveText() const {
        return getString("TargetAlreadyActiveText");
    }
    [[nodiscard]] std::string getRequiresSpecificActionText() const {
        return getString("RequiresSpecificActionText");
    }
};

} // namespace titan
