#pragma once

// LogicBillingPackagesData — typed facade over csv_client/billing_packages.csv (class 2),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicBillingPackagesData : public LogicData {
public:
    LogicBillingPackagesData(const DataTables* tables, int row)
        : LogicData(tables, 2, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] int getType() const {
        return getInt("Type");
    }
    [[nodiscard]] int getTypeCN() const {
        return getInt("TypeCN");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] bool getExistsApple() const {
        return getBool("ExistsApple");
    }
    [[nodiscard]] bool getExistsAndroid() const {
        return getBool("ExistsAndroid");
    }
    [[nodiscard]] bool getExistsCN() const {
        return getBool("ExistsCN");
    }
    [[nodiscard]] bool getDisabledCN() const {
        return getBool("DisabledCN");
    }
    [[nodiscard]] bool getExistsAppleCN() const {
        return getBool("ExistsAppleCN");
    }
    [[nodiscard]] bool getExistsAndroidCN() const {
        return getBool("ExistsAndroidCN");
    }
    [[nodiscard]] int getDiamonds() const {
        return getInt("Diamonds");
    }
    [[nodiscard]] int getUSD() const {
        return getInt("USD");
    }
    [[nodiscard]] int getOrder() const {
        return getInt("Order");
    }
    [[nodiscard]] int getRMB() const {
        return getInt("RMB");
    }
    [[nodiscard]] std::string getTencentID() const {
        return getString("TencentID");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] int getFrameNumber() const {
        return getInt("FrameNumber");
    }
    [[nodiscard]] int getStarterPackNumber() const {
        return getInt("StarterPackNumber");
    }
    [[nodiscard]] int getBigBoxCount() const {
        return getInt("BigBoxCount");
    }
    [[nodiscard]] int getXpLevelReq() const {
        return getInt("XpLevelReq");
    }
    [[nodiscard]] int getValueFactor() const {
        return getInt("ValueFactor");
    }
    [[nodiscard]] std::string getLabelTID() const {
        return getString("LabelTID");
    }
    [[nodiscard]] int getLabelValue() const {
        return getInt("LabelValue");
    }
    [[nodiscard]] int getBg() const {
        return getInt("Bg");
    }
    [[nodiscard]] int getDecor() const {
        return getInt("Decor");
    }
    [[nodiscard]] bool getIsPromotion() const {
        return getBool("IsPromotion");
    }
    [[nodiscard]] int getCoins() const {
        return getInt("Coins");
    }
    [[nodiscard]] int getRefundGemValue() const {
        return getInt("RefundGemValue");
    }
    [[nodiscard]] int getBrawlPassSeason() const {
        return getInt("BrawlPassSeason");
    }
};

} // namespace titan
