#pragma once

// LogicSkillData — typed facade over csv_logic/skills.csv (class 20),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicSkillData : public LogicData {
public:
    LogicSkillData(const DataTables* tables, int row)
        : LogicData(tables, 20, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getBehaviorType() const {
        return getString("BehaviorType");
    }
    [[nodiscard]] bool getCanMoveAtSameTime() const {
        return getBool("CanMoveAtSameTime");
    }
    [[nodiscard]] bool getTargeted() const {
        return getBool("Targeted");
    }
    [[nodiscard]] bool getCanAutoShoot() const {
        return getBool("CanAutoShoot");
    }
    [[nodiscard]] bool getMovementBasedAutoshoot() const {
        return getBool("MovementBasedAutoshoot");
    }
    [[nodiscard]] bool getFaceMovement() const {
        return getBool("FaceMovement");
    }
    [[nodiscard]] int getCooldown() const {
        return getInt("Cooldown");
    }
    [[nodiscard]] int getActiveTime() const {
        return getInt("ActiveTime");
    }
    [[nodiscard]] int getCastingTime() const {
        return getInt("CastingTime");
    }
    [[nodiscard]] int getCastingRange() const {
        return getInt("CastingRange");
    }
    [[nodiscard]] int getRangeVisual() const {
        return getInt("RangeVisual");
    }
    [[nodiscard]] int getRangeInputScale() const {
        return getInt("RangeInputScale");
    }
    [[nodiscard]] int getMaxCastingRange() const {
        return getInt("MaxCastingRange");
    }
    [[nodiscard]] bool getAllowAimOutsideMap() const {
        return getBool("AllowAimOutsideMap");
    }
    [[nodiscard]] int getForceValidTile() const {
        return getInt("ForceValidTile");
    }
    [[nodiscard]] int getRechargeTime() const {
        return getInt("RechargeTime");
    }
    [[nodiscard]] int getMaxCharge() const {
        return getInt("MaxCharge");
    }
    [[nodiscard]] int getDamage() const {
        return getInt("Damage");
    }
    [[nodiscard]] int getPercentDamage() const {
        return getInt("PercentDamage");
    }
    [[nodiscard]] int getMsBetweenAttacks() const {
        return getInt("MsBetweenAttacks");
    }
    [[nodiscard]] int getSpread() const {
        return getInt("Spread");
    }
    [[nodiscard]] int getAttackPattern() const {
        return getInt("AttackPattern");
    }
    [[nodiscard]] int getNumBulletsInOneAttack() const {
        return getInt("NumBulletsInOneAttack");
    }
    [[nodiscard]] bool getTwoGuns() const {
        return getBool("TwoGuns");
    }
    [[nodiscard]] bool getExecuteFirstAttackImmediately() const {
        return getBool("ExecuteFirstAttackImmediately");
    }
    [[nodiscard]] int getChargePushback() const {
        return getInt("ChargePushback");
    }
    [[nodiscard]] int getChargeSpeed() const {
        return getInt("ChargeSpeed");
    }
    [[nodiscard]] int getChargeType() const {
        return getInt("ChargeType");
    }
    [[nodiscard]] int getNumSpawns() const {
        return getInt("NumSpawns");
    }
    [[nodiscard]] int getMaxSpawns() const {
        return getInt("MaxSpawns");
    }
    [[nodiscard]] bool getBreakInvisibilityOnAttack() const {
        return getBool("BreakInvisibilityOnAttack");
    }
    [[nodiscard]] int getSeeInvisibilityDistance() const {
        return getInt("SeeInvisibilityDistance");
    }
    [[nodiscard]] bool getAlwaysCastAtMaxRange() const {
        return getBool("AlwaysCastAtMaxRange");
    }
    [[nodiscard]] std::string getProjectile() const {
        return getString("Projectile");
    }
    [[nodiscard]] std::string getSummonedCharacter() const {
        return getString("SummonedCharacter");
    }
    [[nodiscard]] std::string getAreaEffectObject() const {
        return getString("AreaEffectObject");
    }
    [[nodiscard]] std::string getAreaEffectObject2() const {
        return getString("AreaEffectObject2");
    }
    [[nodiscard]] std::string getSpawnedItem() const {
        return getString("SpawnedItem");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] std::string getLargeIconSWF() const {
        return getString("LargeIconSWF");
    }
    [[nodiscard]] std::string getLargeIconExportName() const {
        return getString("LargeIconExportName");
    }
    [[nodiscard]] std::string getButtonSWF() const {
        return getString("ButtonSWF");
    }
    [[nodiscard]] std::string getButtonExportName() const {
        return getString("ButtonExportName");
    }
    [[nodiscard]] std::string getAttackEffect() const {
        return getString("AttackEffect");
    }
    [[nodiscard]] std::string getUseEffect() const {
        return getString("UseEffect");
    }
    [[nodiscard]] std::string getEndEffect() const {
        return getString("EndEffect");
    }
    [[nodiscard]] std::string getLoopEffect() const {
        return getString("LoopEffect");
    }
    [[nodiscard]] std::string getLoopEffect2() const {
        return getString("LoopEffect2");
    }
    [[nodiscard]] std::string getChargeMoveSound() const {
        return getString("ChargeMoveSound");
    }
    [[nodiscard]] bool getMultiShot() const {
        return getBool("MultiShot");
    }
    [[nodiscard]] bool getSkillCanChange() const {
        return getBool("SkillCanChange");
    }
    [[nodiscard]] bool getShowTimerBar() const {
        return getBool("ShowTimerBar");
    }
    [[nodiscard]] std::string getSecondaryProjectile() const {
        return getString("SecondaryProjectile");
    }
    [[nodiscard]] int getChargedShotCount() const {
        return getInt("ChargedShotCount");
    }
    [[nodiscard]] int getDamageModifier() const {
        return getInt("DamageModifier");
    }
    [[nodiscard]] bool getHoldToShoot() const {
        return getBool("HoldToShoot");
    }
};

} // namespace titan
