#pragma once

// LogicSoundData — typed facade over csv_client/sounds.csv (class 4),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicSoundData : public LogicData {
public:
    LogicSoundData(const DataTables* tables, int row)
        : LogicData(tables, 4, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getFileNames() const {
        return getString("FileNames");
    }
    [[nodiscard]] bool getBackgroundFile() const {
        return getBool("BackgroundFile");
    }
    [[nodiscard]] int getMinVolume() const {
        return getInt("MinVolume");
    }
    [[nodiscard]] int getMaxVolume() const {
        return getInt("MaxVolume");
    }
    [[nodiscard]] int getMinPitch() const {
        return getInt("MinPitch");
    }
    [[nodiscard]] int getMaxPitch() const {
        return getInt("MaxPitch");
    }
    [[nodiscard]] int getPriority() const {
        return getInt("Priority");
    }
    [[nodiscard]] int getMaximumByType() const {
        return getInt("MaximumByType");
    }
    [[nodiscard]] int getMaxRepeatMs() const {
        return getInt("MaxRepeatMs");
    }
    [[nodiscard]] bool getLoop() const {
        return getBool("Loop");
    }
    [[nodiscard]] bool getPlayVariationsInSequence() const {
        return getBool("PlayVariationsInSequence");
    }
    [[nodiscard]] bool getPlayVariationsInSequenceManualReset() const {
        return getBool("PlayVariationsInSequenceManualReset");
    }
    [[nodiscard]] int getStartDelayMinMs() const {
        return getInt("StartDelayMinMs");
    }
    [[nodiscard]] int getStartDelayMaxMs() const {
        return getInt("StartDelayMaxMs");
    }
    [[nodiscard]] bool getPlayOnlyWhenInView() const {
        return getBool("PlayOnlyWhenInView");
    }
    [[nodiscard]] int getMaxVolumeScaleLimit() const {
        return getInt("MaxVolumeScaleLimit");
    }
    [[nodiscard]] int getNoSoundScaleLimit() const {
        return getInt("NoSoundScaleLimit");
    }
    [[nodiscard]] int getPadEmpyToEndMs() const {
        return getInt("PadEmpyToEndMs");
    }
    [[nodiscard]] std::string getMovieClipFrameLabel() const {
        return getString("MovieClipFrameLabel");
    }
};

} // namespace titan
