#pragma once

// LogicMilestone — typed facade over csv_logic/milestones.csv (class 39),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicMilestone : public LogicData {
public:
    LogicMilestone(const DataTables* tables, int row)
        : LogicData(tables, 39, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getType() const {
        return getInt("Type");
    }
    [[nodiscard]] int getIndex() const {
        return getInt("Index");
    }
    [[nodiscard]] int getProgressStart() const {
        return getInt("ProgressStart");
    }
    [[nodiscard]] int getProgress() const {
        return getInt("Progress");
    }
    [[nodiscard]] int getLeague() const {
        return getInt("League");
    }
    [[nodiscard]] int getTier() const {
        return getInt("Tier");
    }
    [[nodiscard]] int getSeason() const {
        return getInt("Season");
    }
    [[nodiscard]] int getHeroPowerUnlock() const {
        return getInt("HeroPowerUnlock");
    }
    [[nodiscard]] int getPrimaryLvlUpRewardType() const {
        return getInt("PrimaryLvlUpRewardType");
    }
    [[nodiscard]] int getPrimaryLvlUpRewardCount() const {
        return getInt("PrimaryLvlUpRewardCount");
    }
    [[nodiscard]] int getPrimaryLvlUpRewardExtraData() const {
        return getInt("PrimaryLvlUpRewardExtraData");
    }
    [[nodiscard]] std::string getPrimaryLvlUpRewardData() const {
        return getString("PrimaryLvlUpRewardData");
    }
    [[nodiscard]] int getSecondaryLvlUpRewardType() const {
        return getInt("SecondaryLvlUpRewardType");
    }
    [[nodiscard]] int getSecondaryLvlUpRewardCount() const {
        return getInt("SecondaryLvlUpRewardCount");
    }
    [[nodiscard]] int getSecondaryLvlUpRewardExtraData() const {
        return getInt("SecondaryLvlUpRewardExtraData");
    }
    [[nodiscard]] std::string getSecondaryLvlUpRewardData() const {
        return getString("SecondaryLvlUpRewardData");
    }
    [[nodiscard]] int getDependsOnIndex() const {
        return getInt("DependsOnIndex");
    }
};

} // namespace titan
