#pragma once

// LogicBossData — typed facade over csv_logic/bosses.csv (class 22),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicBossData : public LogicData {
public:
    LogicBossData(const DataTables* tables, int row)
        : LogicData(tables, 22, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] int getPlayerCount() const {
        return getInt("PlayerCount");
    }
    [[nodiscard]] int getRequiredCampaignProgressToUnlock() const {
        return getInt("RequiredCampaignProgressToUnlock");
    }
    [[nodiscard]] std::string getLocation() const {
        return getString("Location");
    }
    [[nodiscard]] std::string getAllowedHeroes() const {
        return getString("AllowedHeroes");
    }
    [[nodiscard]] std::string getReward() const {
        return getString("Reward");
    }
    [[nodiscard]] int getLevelGenerationSeed() const {
        return getInt("LevelGenerationSeed");
    }
    [[nodiscard]] std::string getMap() const {
        return getString("Map");
    }
    [[nodiscard]] std::string getBoss() const {
        return getString("Boss");
    }
    [[nodiscard]] int getBossLevel() const {
        return getInt("BossLevel");
    }
};

} // namespace titan
