#pragma once

// LogicGlobalData — typed facade over csv_logic/globals.csv (class 3),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicGlobalData : public LogicData {
public:
    LogicGlobalData(const DataTables* tables, int row)
        : LogicData(tables, 3, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getNumberValue() const {
        return getInt("NumberValue");
    }
    [[nodiscard]] bool getBooleanValue() const {
        return getBool("BooleanValue");
    }
    [[nodiscard]] std::string getTextValue() const {
        return getString("TextValue");
    }
    [[nodiscard]] std::string getStringArray() const {
        return getString("StringArray");
    }
    [[nodiscard]] int getNumberArray() const {
        return getInt("NumberArray");
    }
};

} // namespace titan
