#pragma once

// LogicAllianceRoleData — typed facade over csv_logic/alliance_roles.csv (class 25),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicAllianceRoleData : public LogicData {
public:
    LogicAllianceRoleData(const DataTables* tables, int row)
        : LogicData(tables, 25, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getLevel() const {
        return getInt("Level");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] bool getCanInvite() const {
        return getBool("CanInvite");
    }
    [[nodiscard]] bool getCanSendMail() const {
        return getBool("CanSendMail");
    }
    [[nodiscard]] bool getCanChangeAllianceSettings() const {
        return getBool("CanChangeAllianceSettings");
    }
    [[nodiscard]] bool getCanAcceptJoinRequest() const {
        return getBool("CanAcceptJoinRequest");
    }
    [[nodiscard]] bool getCanKick() const {
        return getBool("CanKick");
    }
    [[nodiscard]] bool getCanBePromotedToLeader() const {
        return getBool("CanBePromotedToLeader");
    }
    [[nodiscard]] int getPromoteSkill() const {
        return getInt("PromoteSkill");
    }
};

} // namespace titan
