#pragma once

// LogicCardData — typed facade over csv_logic/cards.csv (class 23),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicCardData : public LogicData {
public:
    LogicCardData(const DataTables* tables, int row)
        : LogicData(tables, 23, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] std::string getTarget() const {
        return getString("Target");
    }
    [[nodiscard]] bool getDisabled() const {
        return getBool("Disabled");
    }
    [[nodiscard]] bool getLockedForChronos() const {
        return getBool("LockedForChronos");
    }
    [[nodiscard]] int getDynamicRarityStartSeason() const {
        return getInt("DynamicRarityStartSeason");
    }
    [[nodiscard]] int getMetaType() const {
        return getInt("MetaType");
    }
    [[nodiscard]] std::string getRequiresCard() const {
        return getString("RequiresCard");
    }
    [[nodiscard]] std::string getType() const {
        return getString("Type");
    }
    [[nodiscard]] std::string getSkill() const {
        return getString("Skill");
    }
    [[nodiscard]] int getValue() const {
        return getInt("Value");
    }
    [[nodiscard]] int getValue2() const {
        return getInt("Value2");
    }
    [[nodiscard]] int getValue3() const {
        return getInt("Value3");
    }
    [[nodiscard]] std::string getRarity() const {
        return getString("Rarity");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getPowerNumberTID() const {
        return getString("PowerNumberTID");
    }
    [[nodiscard]] std::string getPowerNumber2TID() const {
        return getString("PowerNumber2TID");
    }
    [[nodiscard]] std::string getPowerNumber3TID() const {
        return getString("PowerNumber3TID");
    }
    [[nodiscard]] std::string getPowerIcon1ExportName() const {
        return getString("PowerIcon1ExportName");
    }
    [[nodiscard]] std::string getPowerIcon2ExportName() const {
        return getString("PowerIcon2ExportName");
    }
    [[nodiscard]] int getSortOrder() const {
        return getInt("SortOrder");
    }
    [[nodiscard]] bool getDontUpgradeStat() const {
        return getBool("DontUpgradeStat");
    }
    [[nodiscard]] bool getHideDamageStat() const {
        return getBool("HideDamageStat");
    }
};

} // namespace titan
