#pragma once

// LogicShopItemData — typed facade over csv_client/shop_items.csv (class 45),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicShopItemData : public LogicData {
public:
    LogicShopItemData(const DataTables* tables, int row)
        : LogicData(tables, 45, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getOfferType() const {
        return getInt("OfferType");
    }
    [[nodiscard]] bool getAcceptToOffers() const {
        return getBool("AcceptToOffers");
    }
    [[nodiscard]] bool getAcceptToChallengeRewards() const {
        return getBool("AcceptToChallengeRewards");
    }
    [[nodiscard]] int getIconFrameNumber() const {
        return getInt("IconFrameNumber");
    }
    [[nodiscard]] int getMaxResourcePerFrame() const {
        return getInt("MaxResourcePerFrame");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getShopItemAsset() const {
        return getString("ShopItemAsset");
    }
    [[nodiscard]] std::string getPopupItemAsset() const {
        return getString("PopupItemAsset");
    }
    [[nodiscard]] std::string getShopItemBg() const {
        return getString("ShopItemBg");
    }
    [[nodiscard]] std::string getMiniOfferAsset() const {
        return getString("MiniOfferAsset");
    }
    [[nodiscard]] std::string getSeparatedSectionOfferAsset() const {
        return getString("SeparatedSectionOfferAsset");
    }
    [[nodiscard]] std::string getSeparatedSectionTeaseAsset() const {
        return getString("SeparatedSectionTeaseAsset");
    }
    [[nodiscard]] std::string getSeasonalEventOfferAsset() const {
        return getString("SeasonalEventOfferAsset");
    }
    [[nodiscard]] std::string getLegendaryOfferAsset() const {
        return getString("LegendaryOfferAsset");
    }
    [[nodiscard]] std::string getConfirmItemAsset() const {
        return getString("ConfirmItemAsset");
    }
    [[nodiscard]] std::string getConfirmItemBg() const {
        return getString("ConfirmItemBg");
    }
    [[nodiscard]] std::string getOfferAssetSolo() const {
        return getString("OfferAssetSolo");
    }
    [[nodiscard]] std::string getOfferAssetHalf() const {
        return getString("OfferAssetHalf");
    }
    [[nodiscard]] std::string getOfferAssetQuarter() const {
        return getString("OfferAssetQuarter");
    }
    [[nodiscard]] std::string getOfferAssetRankProfile() const {
        return getString("OfferAssetRankProfile");
    }
    [[nodiscard]] std::string getOfferAssetRankLarge() const {
        return getString("OfferAssetRankLarge");
    }
    [[nodiscard]] std::string getSoloOfferBgFrames() const {
        return getString("SoloOfferBgFrames");
    }
    [[nodiscard]] std::string getBrawlPassAssetPaid() const {
        return getString("BrawlPassAssetPaid");
    }
    [[nodiscard]] std::string getBrawlPassAssetFree() const {
        return getString("BrawlPassAssetFree");
    }
    [[nodiscard]] std::string getRankedRewardAsset() const {
        return getString("RankedRewardAsset");
    }
    [[nodiscard]] std::string getRankedGoalAsset() const {
        return getString("RankedGoalAsset");
    }
    [[nodiscard]] std::string getRankedGoalQuestAsset() const {
        return getString("RankedGoalQuestAsset");
    }
    [[nodiscard]] std::string getRewardDescTID() const {
        return getString("RewardDescTID");
    }
    [[nodiscard]] std::string getChallengeRewardFrame() const {
        return getString("ChallengeRewardFrame");
    }
    [[nodiscard]] std::string getChallengeRewardAsset() const {
        return getString("ChallengeRewardAsset");
    }
};

} // namespace titan
