#pragma once

// LogicLocaleData — typed facade over csv_logic/locales.csv (class 1),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicLocaleData : public LogicData {
public:
    LogicLocaleData(const DataTables* tables, int row)
        : LogicData(tables, 1, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getIconSWF() const {
        return getString("IconSWF");
    }
    [[nodiscard]] std::string getIconExportName() const {
        return getString("IconExportName");
    }
    [[nodiscard]] std::string getLocalizedName() const {
        return getString("LocalizedName");
    }
    [[nodiscard]] int getSortOrder() const {
        return getInt("SortOrder");
    }
    [[nodiscard]] bool getEnabled() const {
        return getBool("Enabled");
    }
    [[nodiscard]] bool getEnabledCN() const {
        return getBool("EnabledCN");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] bool getTestLanguage() const {
        return getBool("TestLanguage");
    }
    [[nodiscard]] std::string getUsedSystemFont() const {
        return getString("UsedSystemFont");
    }
    [[nodiscard]] std::string getPreferedFallbackFont() const {
        return getString("PreferedFallbackFont");
    }
    [[nodiscard]] std::string getForcedFontFullName() const {
        return getString("ForcedFontFullName");
    }
    [[nodiscard]] std::string getHelpshiftSDKLanguage() const {
        return getString("HelpshiftSDKLanguage");
    }
    [[nodiscard]] std::string getHelpshiftSDKLanguageAndroid() const {
        return getString("HelpshiftSDKLanguageAndroid");
    }
    [[nodiscard]] std::string getTestExcludes() const {
        return getString("TestExcludes");
    }
    [[nodiscard]] bool getLoadAllLanguages() const {
        return getBool("LoadAllLanguages");
    }
    [[nodiscard]] std::string getChampionshipRegisterUrl() const {
        return getString("ChampionshipRegisterUrl");
    }
    [[nodiscard]] std::string getChampionshipRegisterUrl_cn() const {
        return getString("ChampionshipRegisterUrl_cn");
    }
    [[nodiscard]] std::string getTermsAndServiceUrl() const {
        return getString("TermsAndServiceUrl");
    }
    [[nodiscard]] std::string getParentsGuideUrl() const {
        return getString("ParentsGuideUrl");
    }
    [[nodiscard]] std::string getPrivacyPolicyUrl() const {
        return getString("PrivacyPolicyUrl");
    }
    [[nodiscard]] std::string getLaserboxUrl() const {
        return getString("LaserboxUrl");
    }
    [[nodiscard]] std::string getLaserboxUrlCN() const {
        return getString("LaserboxUrlCN");
    }
    [[nodiscard]] std::string getLaserboxStagingUrl() const {
        return getString("LaserboxStagingUrl");
    }
    [[nodiscard]] std::string getLaserboxStagingUrlCN() const {
        return getString("LaserboxStagingUrlCN");
    }
    [[nodiscard]] std::string getLaserboxCommunityUrl() const {
        return getString("LaserboxCommunityUrl");
    }
    [[nodiscard]] std::string getLaserboxCommunityUrlCN() const {
        return getString("LaserboxCommunityUrlCN");
    }
    [[nodiscard]] std::string getLaserboxCommunityStagingUrl() const {
        return getString("LaserboxCommunityStagingUrl");
    }
    [[nodiscard]] std::string getLaserboxCommunityStagingUrlCN() const {
        return getString("LaserboxCommunityStagingUrlCN");
    }
    [[nodiscard]] std::string getLaserboxEsportsUrl() const {
        return getString("LaserboxEsportsUrl");
    }
    [[nodiscard]] std::string getLaserboxEsportsUrlCN() const {
        return getString("LaserboxEsportsUrlCN");
    }
    [[nodiscard]] std::string getLaserboxEsportsStagingUrl() const {
        return getString("LaserboxEsportsStagingUrl");
    }
    [[nodiscard]] std::string getLaserboxEsportsStagingUrlCN() const {
        return getString("LaserboxEsportsStagingUrlCN");
    }
    [[nodiscard]] std::string getLaserboxEsportsHubUrl() const {
        return getString("LaserboxEsportsHubUrl");
    }
    [[nodiscard]] std::string getLaserboxEsportsHubUrlCN() const {
        return getString("LaserboxEsportsHubUrlCN");
    }
    [[nodiscard]] std::string getLaserboxEsportsHubStagingUrl() const {
        return getString("LaserboxEsportsHubStagingUrl");
    }
    [[nodiscard]] std::string getLaserboxEsportsHubStagingUrlCN() const {
        return getString("LaserboxEsportsHubStagingUrlCN");
    }
    [[nodiscard]] std::string getLaserboxLangCode() const {
        return getString("LaserboxLangCode");
    }
    [[nodiscard]] std::string getFaqUrl_ios() const {
        return getString("FaqUrl_ios");
    }
    [[nodiscard]] std::string getFaqUrl_ios_cn() const {
        return getString("FaqUrl_ios_cn");
    }
    [[nodiscard]] std::string getFaqUrl_android() const {
        return getString("FaqUrl_android");
    }
    [[nodiscard]] std::string getFaqUrl_android_cn() const {
        return getString("FaqUrl_android_cn");
    }
    [[nodiscard]] std::string getContactUsUrl_ios() const {
        return getString("ContactUsUrl_ios");
    }
    [[nodiscard]] std::string getContactUsUrl_ios_cn() const {
        return getString("ContactUsUrl_ios_cn");
    }
    [[nodiscard]] std::string getContactUsUrl_android() const {
        return getString("ContactUsUrl_android");
    }
    [[nodiscard]] std::string getContactUsUrl_android_cn() const {
        return getString("ContactUsUrl_android_cn");
    }
    [[nodiscard]] bool getLaserboxEnabled() const {
        return getBool("LaserboxEnabled");
    }
    [[nodiscard]] bool getIsRTL() const {
        return getBool("IsRTL");
    }
    [[nodiscard]] bool getisNounAdj() const {
        return getBool("isNounAdj");
    }
    [[nodiscard]] bool getSeparateThousandsWithSpaces() const {
        return getBool("SeparateThousandsWithSpaces");
    }
    [[nodiscard]] bool getUseWhiteSpaceToReplaceLineBreak() const {
        return getBool("UseWhiteSpaceToReplaceLineBreak");
    }
    [[nodiscard]] bool getUsesWhiteSpacesBetweenWords() const {
        return getBool("UsesWhiteSpacesBetweenWords");
    }
    [[nodiscard]] std::string getSelfHelpUrl() const {
        return getString("SelfHelpUrl");
    }
    [[nodiscard]] std::string getSelfHelpUrlCN() const {
        return getString("SelfHelpUrlCN");
    }
    [[nodiscard]] bool getFallbackToHelpshift() const {
        return getBool("FallbackToHelpshift");
    }
    [[nodiscard]] bool getFallbackToHelpshiftCN() const {
        return getBool("FallbackToHelpshiftCN");
    }
    [[nodiscard]] std::string getTermsAndServiceUrl_Tencent_android() const {
        return getString("TermsAndServiceUrl_Tencent_android");
    }
    [[nodiscard]] std::string getParentsGuideUrl_Tencent_android() const {
        return getString("ParentsGuideUrl_Tencent_android");
    }
    [[nodiscard]] std::string getPrivacyPolicyUrl_Tencent_android() const {
        return getString("PrivacyPolicyUrl_Tencent_android");
    }
    [[nodiscard]] std::string getTermsAndServiceUrl_Tencent_ios() const {
        return getString("TermsAndServiceUrl_Tencent_ios");
    }
    [[nodiscard]] std::string getParentsGuideUrl_Tencent_ios() const {
        return getString("ParentsGuideUrl_Tencent_ios");
    }
    [[nodiscard]] std::string getPrivacyPolicyUrl_Tencent_ios() const {
        return getString("PrivacyPolicyUrl_Tencent_ios");
    }
    [[nodiscard]] std::string getTermsAndServiceUrl_Yoozoo() const {
        return getString("TermsAndServiceUrl_Yoozoo");
    }
    [[nodiscard]] std::string getParentsGuideUrl_Yoozoo() const {
        return getString("ParentsGuideUrl_Yoozoo");
    }
    [[nodiscard]] std::string getPrivacyPolicyUrl_Yoozoo() const {
        return getString("PrivacyPolicyUrl_Yoozoo");
    }
    [[nodiscard]] std::string getDeviceMigrationSelfHelpUrl() const {
        return getString("DeviceMigrationSelfHelpUrl");
    }
};

} // namespace titan
