#pragma once

// LogicHealthBarData — typed facade over csv_client/health_bars.csv (class 11),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicHealthBarData : public LogicData {
public:
    LogicHealthBarData(const DataTables* tables, int row)
        : LogicData(tables, 11, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getPlayerExportNameTop() const {
        return getString("PlayerExportNameTop");
    }
    [[nodiscard]] std::string getPlayerExportNameBot() const {
        return getString("PlayerExportNameBot");
    }
    [[nodiscard]] std::string getEnemyExportNameTop() const {
        return getString("EnemyExportNameTop");
    }
    [[nodiscard]] std::string getEnemyExportNameBot() const {
        return getString("EnemyExportNameBot");
    }
    [[nodiscard]] std::string getYourTeamExportNameTop() const {
        return getString("YourTeamExportNameTop");
    }
    [[nodiscard]] std::string getYourTeamExportNameBot() const {
        return getString("YourTeamExportNameBot");
    }
};

} // namespace titan
