#pragma once

// LogicLocalNotificationData — typed facade over csv_client/local_notifications.csv (class 51),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicLocalNotificationData : public LogicData {
public:
    LogicLocalNotificationData(const DataTables* tables, int row)
        : LogicData(tables, 51, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getPriority() const {
        return getInt("Priority");
    }
    [[nodiscard]] std::string getNotificationText() const {
        return getString("NotificationText");
    }
    [[nodiscard]] bool getIsRegularEventRefresh() const {
        return getBool("IsRegularEventRefresh");
    }
    [[nodiscard]] bool getDontCompare() const {
        return getBool("DontCompare");
    }
    [[nodiscard]] bool getAutoAdd() const {
        return getBool("AutoAdd");
    }
    [[nodiscard]] int getTimeOffsetMins() const {
        return getInt("TimeOffsetMins");
    }
    [[nodiscard]] int getMaxRandomTimeOffsetMins() const {
        return getInt("MaxRandomTimeOffsetMins");
    }
    [[nodiscard]] int getCheckRangeMins() const {
        return getInt("CheckRangeMins");
    }
};

} // namespace titan
