#pragma once

// LogicRegionData — typed facade over csv_logic/regions.csv (class 14),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicRegionData : public LogicData {
public:
    LogicRegionData(const DataTables* tables, int row)
        : LogicData(tables, 14, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] std::string getDisplayName() const {
        return getString("DisplayName");
    }
    [[nodiscard]] bool getIsCountry() const {
        return getBool("IsCountry");
    }
};

} // namespace titan
