#pragma once

// LogicHintData — typed facade over csv_client/hints.csv (class 36),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicHintData : public LogicData {
public:
    LogicHintData(const DataTables* tables, int row)
        : LogicData(tables, 36, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getTID() const {
        return getString("TID");
    }
    [[nodiscard]] int getMinXPLevel() const {
        return getInt("MinXPLevel");
    }
    [[nodiscard]] int getMaxXPLevel() const {
        return getInt("MaxXPLevel");
    }
    [[nodiscard]] std::string getFileName() const {
        return getString("FileName");
    }
    [[nodiscard]] std::string getExportName() const {
        return getString("ExportName");
    }
    [[nodiscard]] std::string getCharacter() const {
        return getString("Character");
    }
    [[nodiscard]] bool getReferringSCID() const {
        return getBool("ReferringSCID");
    }
};

} // namespace titan
