#pragma once

// LogicLinkData — typed facade over csv_client/links.csv (class 42),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicLinkData : public LogicData {
public:
    LogicLinkData(const DataTables* tables, int row)
        : LogicData(tables, 42, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getLanguage() const {
        return getString("Language");
    }
    [[nodiscard]] std::string getURL() const {
        return getString("URL");
    }
};

} // namespace titan
