#pragma once

// LogicPinData — typed facade over csv_logic/pins.csv (class 35),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicPinData : public LogicData {
public:
    LogicPinData(const DataTables* tables, int row)
        : LogicData(tables, 35, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] int getPinType() const {
        return getInt("PinType");
    }
    [[nodiscard]] int getRarity() const {
        return getInt("Rarity");
    }
    [[nodiscard]] int getIndex() const {
        return getInt("Index");
    }
    [[nodiscard]] int getBonus() const {
        return getInt("Bonus");
    }
    [[nodiscard]] int getCraftCost() const {
        return getInt("CraftCost");
    }
};

} // namespace titan
