#pragma once

// LogicData — base of the typed CSV data facades (cf. LogicData::setCSVRow
// @0x492068, getAndAssert*ColumnIndex). A LogicData binds (table, row);
// typed getters read by column name through CsvTable. Per-table facades
// (LogicCharacterData, …) are generated by tools/gen_dataclasses.py from
// the CSV headers, one class per table.

#include "titan/game/CsvTable.hpp"
#include "titan/game/DataTables.hpp"

namespace titan {

class LogicData {
public:
    LogicData(const DataTables* tables, int classId, int row)
        : tables_(tables), classId_(classId), row_(row) {}

    [[nodiscard]] int classId() const { return classId_; }
    [[nodiscard]] int row() const { return row_; }
    [[nodiscard]] const DataTables* dataTables() const { return tables_; }
    // getDataType @0x35bf58 = parent table index == class id.
    [[nodiscard]] int getDataType() const { return classId_; }
    [[nodiscard]] bool equals(const LogicData& o) const {
        return classId_ == o.classId_ && row_ == o.row_;
    }
    [[nodiscard]] int globalId() const {
        return GlobalID::make(classId_, row_);
    }
    [[nodiscard]] bool valid() const {
        return tables_ != nullptr && tables_->table(classId_) != nullptr
               && row_ >= 0
               && row_ < tables_->table(classId_)->rows.size();
    }

    [[nodiscard]] std::string getString(const std::string& col,
                                        const std::string& fallback = "") const {
        const CsvTable* t = table();
        return t ? t->get(row_, col, fallback) : fallback;
    }
    [[nodiscard]] int getInt(const std::string& col, int fallback = 0) const {
        const CsvTable* t = table();
        return t ? t->getInt(row_, col, fallback) : fallback;
    }
    [[nodiscard]] bool getBool(const std::string& col, bool fallback = false) const {
        const CsvTable* t = table();
        return t ? t->getBool(row_, col, fallback) : fallback;
    }

protected:
    [[nodiscard]] const CsvTable* table() const {
        return tables_ ? tables_->table(classId_) : nullptr;
    }

    const DataTables* tables_ = nullptr;
    int classId_ = -1;
    int row_ = -1;
};

} // namespace titan
