#pragma once

// LogicSkinCampaignData — typed facade over csv_logic/skin_campaigns.csv (class 57),
// generated by tools/gen_dataclasses.py from the CSV header.

#include "titan/game/LogicData.hpp"

#include <string>

namespace titan {

class LogicSkinCampaignData : public LogicData {
public:
    LogicSkinCampaignData(const DataTables* tables, int row)
        : LogicData(tables, 57, row) {}

    [[nodiscard]] std::string getName() const {
        return getString("Name");
    }
    [[nodiscard]] std::string getInfoTID() const {
        return getString("InfoTID");
    }
    [[nodiscard]] std::string getBgItemName() const {
        return getString("BgItemName");
    }
    [[nodiscard]] bool getSkinBuyRequiresExclusiveOption() const {
        return getBool("SkinBuyRequiresExclusiveOption");
    }
};

} // namespace titan
