#!/usr/bin/env python3
"""Generate typed Logic<Data> facades from the CSV headers (one class per table).

Each facade wraps LogicData with one getter per CSV column, typed by the
CSV types row (int/boolean/string). Class names follow the binary
convention (verified against Logic*Data C2 symbols in data/ida_shard_*.csv);
tables without a known binary class get a derived name + REVIEW mark.

NOT registry-counted: facades are column-driven, not per-function reverses.

Run:  python3 tools/gen_dataclasses.py
Out:  titan/game/data/Logic<X>Data.cpp
"""
import csv
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "titan", "game", "data")
MAP = os.path.join(ROOT, "data", "datatable_map.csv")
ASSETS = os.environ.get("TITAN_ASSETS",
                         os.path.join(ROOT, "assets"))

# csv basename -> FULL binary class name (only where the dumb rule fails).
# Tables without a local CSV (achievements, gem_bundles, helpshift,
# xp_levels) have no facade by construction.
OVERRIDES = {
    "billing_packages": "LogicBillingPackagesData",
    "credits": "LogicCreditsData",          # REVIEW: no C2 symbol found
    "maps": "LogicMapData",                 # REVIEW: no C2 symbol found
    "map_templates": "LogicMapTemplateData",  # REVIEW: no C2 symbol found
    "milestones": "LogicMilestone",
    "skinsrarity": "LogicSkinRarityData",
    "tutorial": "LogicTutorialStepData",
}


# csv basenames with no binary C2 symbol found (derived names, need review).
REVIEW = {"credits", "maps", "map_templates"}


def singular(word):
    if word.endswith("ies"):
        return word[:-3] + "y"
    if re.search(r"(ss|sh|ch|x|z)es$", word):
        return word[:-2]
    if word.endswith("s") and not word.endswith("ss"):
        return word[:-1]
    return word


def classname(basename):
    if basename in OVERRIDES:
        return OVERRIDES[basename]
    parts = [singular(w) for w in basename.split("_")]
    stem = "".join(w[:1].upper() + w[1:] for w in parts)
    return "Logic" + stem + "Data"


def ident(col):
    name = re.sub(r"\W", "_", col.strip())
    if not name:
        return "empty"
    if name[0].isdigit():
        name = "C" + name
    return name


TYPEMAP = {"int": ("int", "getInt"), "boolean": ("bool", "getBool"),
           "Boolean": ("bool", "getBool"), "string": ("std::string", "getString"),
           "String": ("std::string", "getString"),
           "StringArray": ("std::string", "getString")}


def emit(class_id, csv_rel, cls):
    path = os.path.join(ASSETS, csv_rel)
    with open(path, encoding="utf-8-sig", newline="") as fh:
        reader = csv.reader(fh)
        cols = next(reader)
        typs = next(reader, [])
    while len(typs) < len(cols):
        typs.append("string")
    review = ""
    if os.path.splitext(os.path.basename(csv_rel))[0] in REVIEW:
        review = ("  // REVIEW: class name derived, "
                  "no binary C2 symbol found.\n")
    getters = []
    for col, typ in zip(cols, typs):
        if not col.strip():
            continue
        ctype, fn = TYPEMAP.get(typ.strip(), ("std::string", "getString"))
        name = ident(col)
        if ctype == "std::string":
            getters.append(
                f"    [[nodiscard]] std::string get{name}() const {{\n"
                f"        return getString(\"{col}\");\n    }}")
        elif ctype == "bool":
            getters.append(
                f"    [[nodiscard]] bool get{name}() const {{\n"
                f"        return getBool(\"{col}\");\n    }}")
        else:
            getters.append(
                f"    [[nodiscard]] int get{name}() const {{\n"
                f"        return getInt(\"{col}\");\n    }}")
    body = ("#pragma once\n\n"
            f"// {cls} — typed facade over {csv_rel} (class {class_id}),\n"
            "// generated by tools/gen_dataclasses.py from the CSV header.\n"
            + review +
            "\n#include \"titan/game/data/LogicData.cpp\"\n\n"
            "#include <string>\n\n"
            "namespace titan {\n\n"
            f"class {cls} : public LogicData {{\npublic:\n"
            f"    {cls}(const DataTables* tables, int row)\n"
            f"        : LogicData(tables, {class_id}, row) {{}}\n\n"
            + "\n".join(getters)
            + "\n};\n\n} // namespace titan\n")
    with open(os.path.join(OUT, cls + ".cpp"), "w", encoding="utf-8") as fh:
        fh.write(body)
    return cls


def main():
    made = []
    with open(MAP, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(",")
            class_id = int(parts[0])
            csv_rel = parts[1].strip()
            if csv_rel == "EMPTY":
                continue
            base = os.path.splitext(os.path.basename(csv_rel))[0]
            made.append(emit(class_id, csv_rel, classname(base)))
    print("data classes:", len(made))
    print(" ".join(sorted(made)))


if __name__ == "__main__":
    main()
