#!/usr/bin/env python3
"""Generate the message factory from data/message_ids.json.

LogicLaserMessageFactory (0x513e58) maps numeric type -> message class.
This port generates the same table mechanically from IDA getters, so every
class keeps the exact id the binary reports.

Duplicate ids are genuine in the binary (both getters return the same
value); the factory picks the first alphabetically and lists the others
in a comment until version-based disambiguation is reversed.

Run:  python tools/generate_factory.py
Out:  titan/gen/MessageFactory.hpp, titan/gen/MessageFactory.cpp
"""
import glob
import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Classes found only via the factory (batch 14), absent from message_index.
EXTRA_IDS = {
    "LoginMessage": 10101,
    "AcceptFriendMessage": 10501,
    "AskForFriendListMessage": 10504,
    "RemoveFriendMessage": 10506,
    "AskForFriendSuggestionsMessage": 10599,
    "GetTokenFriendMessage": 15793,
    "GetAllianceInviteTokenMessage": 10309,
    "LoginFailedMessage": 20103,
    "ExtendedSetEncryptionMessage": 20000,
    "ResetAccountMessage": 10116,
    "KeepAliveMessage": 10108,
    "KeepAliveServerMessage": 20108,
}

# Class -> source TU (families own their classes; specials listed explicitly).
HEADER_OF = {
    "ResetAccountMessage": "titan/messages/account/ResetAccountMessage.cpp",
    "KeepAliveMessage": "titan/messages/account/KeepAliveMessage.cpp",
    "KeepAliveServerMessage": "titan/messages/account/KeepAliveServerMessage.cpp",
}


def header_for(cls, batches):
    if cls in HEADER_OF:
        return HEADER_OF[cls]
    hits = sorted(glob.glob(os.path.join(ROOT, "titan", "messages", "*", cls + ".cpp")))
    if hits:
        return os.path.relpath(hits[0], ROOT)
    raise KeyError(cls)


def main():
    ids = json.load(open(os.path.join(ROOT, "data", "message_ids.json")))
    ids.update(EXTRA_IDS)
    batches = json.load(open(os.path.join(ROOT, "data", "message_batches.json")))
    batch_of = {}
    for n, members in enumerate(batches):
        for m in members:
            batch_of[m] = n
    for m in EXTRA_IDS:
        batch_of[m] = 14

    by_id = defaultdict(list)
    for cls, i in ids.items():
        by_id[i].append(cls)

    headers = sorted({header_for(c, {n: batches[n] for n in range(len(batches))})
                      for c in ids})

    gen_inc = os.path.join(ROOT, "titan", "gen")
    gen_src = os.path.join(ROOT, "titan", "gen")
    os.makedirs(gen_inc, exist_ok=True)
    os.makedirs(gen_src, exist_ok=True)

    with open(os.path.join(gen_inc, "MessageFactory.hpp"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("""#pragma once

// Generated by tools/generate_factory.py — do not edit by hand.
// Mirrors LogicLaserMessageFactory (0x513e58): numeric type -> message.

#include "titan/core/PiranhaMessage.hpp"

#include <cstdint>
#include <memory>

namespace titan {

std::unique_ptr<PiranhaMessage> createMessageByType(int type);

} // namespace titan
""")

    dup = {i: v for i, v in by_id.items() if len(v) > 1}
    with open(os.path.join(gen_src, "MessageFactory.cpp"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated — do not edit. %d ids, %d classes.\n" %
                 (len(by_id), len(ids)))
        for h in headers:
            fh.write('#include "%s"\n' % h)
        fh.write("\nnamespace titan {\n\n")
        fh.write("std::unique_ptr<PiranhaMessage> createMessageByType(int type) {\n"
                 "    switch (type) {\n")
        for i in sorted(by_id):
            first = sorted(by_id[i])[0]
            if len(by_id[i]) > 1:
                fh.write("        // collision (see data/factory_notes.csv): %s\n" %
                         ", ".join(sorted(by_id[i])[1:]))
            fh.write("        case %d: return std::make_unique<%s>();\n" % (i, first))
        fh.write("        default: return nullptr;\n"
                 "    }\n"
                 "}\n\n} // namespace titan\n")
    print(f"ids: {len(by_id)} classes: {len(ids)} collisions: {sorted(dup)}")


if __name__ == "__main__":
    main()
