#!/usr/bin/env python3
"""Generate pending LogicCommand subclasses + factory from data/command_table.csv.

Mirrors LogicCommandManager::createCommand (0x7c41d8). Subclass BODIES are
pending reverse: overrides throw pending_reverse until their wave lands;
the base prefix (LogicCommand::encode/decode) is real.

Run:  python tools/generate_commands.py
Out:  include/titan/gen/LogicCommands.hpp, src/gen/LogicCommands.cpp
"""
import csv
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    rows = []
    with open(os.path.join(ROOT, "data", "command_table.csv")) as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#") or "," not in line:
                continue
            t, c = line.split(",", 1)
            if not t.strip().lstrip("-").isdigit():
                continue
            rows.append((int(t.strip()), c.strip()))

    # Classes with handwritten bodies (src/commands/) are skipped here;
    # the factory still covers them via HANDWRITTEN below.
    done = set()
    done_path = os.path.join(ROOT, "data", "commands_done.txt")
    if os.path.exists(done_path):
        with open(done_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line and not line.startswith("#"):
                    done.add(line)

    gen_inc = os.path.join(ROOT, "include", "titan", "gen")
    gen_src = os.path.join(ROOT, "src", "gen")
    os.makedirs(gen_inc, exist_ok=True)
    os.makedirs(gen_src, exist_ok=True)

    with open(os.path.join(gen_inc, "LogicCommands.hpp"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("""#pragma once

// Generated by tools/generate_commands.py — do not edit by hand.
// Mirrors LogicCommandManager::createCommand (0x7c41d8).
// Subclass bodies throw pending_reverse until reversed; edit the generator
// output only by re-running after adding real bodies elsewhere.

#include "titan/commands/LogicCommand.hpp"

#include <memory>

namespace titan {

std::unique_ptr<LogicCommand> createCommandByType(int type);

// Manager shapes (encode @0x85e668 / decode @0x38a110;
// single encodeCommand @0x870160 / decodeCommand @0x2b856c).
void encodeCommandList(ByteStream& s,
                       const std::vector<std::unique_ptr<LogicCommand>>& cmds);
void decodeCommandList(ByteStream& s,
                       std::vector<std::unique_ptr<LogicCommand>>& cmds);
void encodeSingleCommand(ByteStream& s, const std::unique_ptr<LogicCommand>& c);
std::unique_ptr<LogicCommand> decodeSingleCommand(ByteStream& s);

""")
        for t, c in rows:
            if c == "LogicCommand":
                continue  # base itself (type 511); see below
            if c in done:
                continue  # handwritten real body in src/commands/
            fh.write("class %s : public LogicCommand {\n"
                     "public:\n"
                     "    int getCommandType() const override { return %d; }\n"
                     "    void encode(ByteStream&) const override {\n"
                     "        throw pending_reverse(\"%s pending reverse\");\n"
                     "    }\n"
                     "    void decode(ByteStream&) override {\n"
                     "        throw pending_reverse(\"%s pending reverse\");\n"
                     "    }\n"
                     "};\n\n" % (c, t, c, c))
        fh.write("// Type 511 instantiates the base vtable in the binary.\n"
                 "class LogicCommandBase511 : public LogicCommand {\n"
                 "public:\n"
                 "    int getCommandType() const override { return 511; }\n"
                 "};\n\n} // namespace titan\n")

    with open(os.path.join(gen_src, "LogicCommands.cpp"), "w",
              encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated — do not edit.\n"
                 '#include "titan/gen/LogicCommands.hpp"\n')
        import glob as _glob
        for path in sorted(_glob.glob(os.path.join(
                ROOT, "include", "titan", "commands", "Logic*Command.hpp"))):
            fh.write('#include "titan/commands/%s"\n'
                     % os.path.basename(path))
        fh.write("\nnamespace titan {\n\n"
                 "std::unique_ptr<LogicCommand> createCommandByType(int type) {\n"
                 "    switch (type) {\n")
        for t, c in rows:
            target = "LogicCommandBase511" if c == "LogicCommand" else c
            fh.write("        case %d: return std::make_unique<%s>();\n" % (t, target))
        fh.write("        default: return nullptr;\n"
                 "    }\n"
                 "}\n\n"
                 "void encodeCommandList(ByteStream& s,\n"
                 "                       const std::vector<std::unique_ptr<LogicCommand>>& cmds) {\n"
                 "    s.writeVInt(static_cast<i32>(cmds.size()));\n"
                 "    for (const auto& c : cmds) encodeSingleCommand(s, c);\n"
                 "}\n\n"
                 "void decodeCommandList(ByteStream& s,\n"
                 "                       std::vector<std::unique_ptr<LogicCommand>>& cmds) {\n"
                 "    const i32 n = s.readVInt();\n"
                 "    cmds.clear();\n"
                 "    for (i32 i = 0; i < n; ++i) cmds.push_back(decodeSingleCommand(s));\n"
                 "}\n\n"
                 "void encodeSingleCommand(ByteStream& s, const std::unique_ptr<LogicCommand>& c) {\n"
                 "    if (!c) throw std::runtime_error(\"null command\");\n"
                 "    s.writeVInt(c->getCommandType());\n"
                 "    c->encode(s);\n"
                 "}\n\n"
                 "std::unique_ptr<LogicCommand> decodeSingleCommand(ByteStream& s) {\n"
                 "    auto c = createCommandByType(s.readVInt());\n"
                 "    if (!c) throw std::runtime_error(\"unknown command type\");\n"
                 "    c->decode(s);\n"
                 "    return c;\n"
                 "}\n\n} // namespace titan\n")
    print(f"commands: {len(rows)}")


if __name__ == "__main__":
    main()
