#!/usr/bin/env python3
"""Regenerate AllMessages.cpp / AllCommands.hpp from per-class files on disk."""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

msg = sorted(
    os.path.relpath(p, os.path.join(ROOT, "titan", "messages"))[:-4]
    for p in glob.glob(os.path.join(ROOT, "titan", "messages", "*", "*.cpp")))
with open(os.path.join(ROOT, "titan", "messages", "AllMessages.cpp"),
          "w", encoding="utf-8", newline="\n") as fh:
    fh.write("#pragma once\n\n// Generated by tools/regen_aggregates.py — all messages.\n\n")
    for cls in msg:
        fh.write('#include "titan/messages/%s.cpp"\n' % cls)

cmd = sorted(
    os.path.splitext(os.path.basename(p))[0]
    for p in glob.glob(os.path.join(ROOT, "titan", "commands", "*.hpp"))
    if os.path.basename(p) not in ("AllCommands.hpp", "LogicCommand.hpp"))
with open(os.path.join(ROOT, "titan", "commands", "AllCommands.hpp"),
          "w", encoding="utf-8", newline="\n") as fh:
    fh.write("#pragma once\n\n// Generated by tools/regen_aggregates.py — all commands.\n\n")
    for cls in cmd:
        fh.write('#include "titan/commands/%s.hpp"\n' % cls)

print("messages:", len(msg), "commands:", len(cmd))
