#!/usr/bin/env python3
"""Regenerate AllMessages.hpp / AllCommands.hpp from per-class files on disk."""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

msg = sorted(
    os.path.splitext(os.path.basename(p))[0]
    for p in glob.glob(os.path.join(ROOT, "include", "titan", "messages", "*.hpp"))
    if os.path.basename(p) not in ("AllMessages.hpp", "MessagePrelude.hpp",
                                   "Nested.hpp", "Common.hpp"))
with open(os.path.join(ROOT, "include", "titan", "messages", "AllMessages.hpp"),
          "w", encoding="utf-8", newline="\n") as fh:
    fh.write("#pragma once\n\n// Generated by tools/regen_aggregates.py — all messages.\n\n")
    for cls in msg:
        fh.write('#include "titan/messages/%s.hpp"\n' % cls)

cmd = sorted(
    os.path.splitext(os.path.basename(p))[0]
    for p in glob.glob(os.path.join(ROOT, "include", "titan", "commands", "*.hpp"))
    if os.path.basename(p) not in ("AllCommands.hpp", "LogicCommand.hpp"))
with open(os.path.join(ROOT, "include", "titan", "commands", "AllCommands.hpp"),
          "w", encoding="utf-8", newline="\n") as fh:
    fh.write("#pragma once\n\n// Generated by tools/regen_aggregates.py — all commands.\n\n")
    for cls in cmd:
        fh.write('#include "titan/commands/%s.hpp"\n' % cls)

print("messages:", len(msg), "commands:", len(cmd))
